// SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause)
//
// THIS FILE IS AUTOGENERATED BY CARGO-LIBBPF-GEN!

pub use self::imp::*;

#[allow(dead_code)]
#[allow(non_snake_case)]
#[allow(non_camel_case_types)]
#[allow(clippy::absolute_paths)]
#[allow(clippy::upper_case_acronyms)]
#[allow(clippy::zero_repeat_side_effects)]
#[warn(single_use_lifetimes)]
mod imp {
    #[allow(unused_imports)]
    use super::*;
    use libbpf_rs::libbpf_sys;
    use libbpf_rs::skel::OpenSkel;
    use libbpf_rs::skel::Skel;
    use libbpf_rs::skel::SkelBuilder;
    use libbpf_rs::AsRawLibbpf as _;
    use libbpf_rs::MapCore as _;
    fn build_skel_config(
    ) -> libbpf_rs::Result<libbpf_rs::__internal_skel::ObjectSkeletonConfig<'static>> {
        let mut builder = libbpf_rs::__internal_skel::ObjectSkeletonConfigBuilder::new(DATA);
        builder
            .name("sslsnoop_bpf")
            .map("events", false)
            .map("ssl_buffers", false)
            .map("sslsnoop.rodata", true)
            .prog("probe_func")
            .prog("retprobe_read")
            .prog("retprobe_write");
        builder.build()
    }
    pub struct OpenSslsnoopMaps<'obj> {
        pub events: libbpf_rs::OpenMapMut<'obj>,
        pub ssl_buffers: libbpf_rs::OpenMapMut<'obj>,
        pub rodata: libbpf_rs::OpenMapMut<'obj>,
        pub rodata_data: &'obj mut types::rodata,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> OpenSslsnoopMaps<'obj> {
        #[allow(unused_variables)]
        unsafe fn new(
            config: &libbpf_rs::__internal_skel::ObjectSkeletonConfig<'_>,
            object: &mut libbpf_rs::OpenObject,
        ) -> libbpf_rs::Result<Self> {
            let mut events = None;
            let mut ssl_buffers = None;
            let mut rodata = None;
            let object = unsafe {
                std::mem::transmute::<&mut libbpf_rs::OpenObject, &'obj mut libbpf_rs::OpenObject>(
                    object,
                )
            };
            #[allow(clippy::never_loop)]
            for map in object.maps_mut() {
                let name = map.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "map has invalid name",
                    ))
                })?;
                #[allow(clippy::match_single_binding)]
                match name {
                    "events" => events = Some(map),
                    "ssl_buffers" => ssl_buffers = Some(map),
                    "sslsnoop.rodata" => rodata = Some(map),
                    _ => panic!("encountered unexpected map: `{name}`"),
                }
            }

            let slf = Self {
                events: events.expect("map `events` not present"),
                ssl_buffers: ssl_buffers.expect("map `ssl_buffers` not present"),
                rodata: rodata.expect("map `rodata` not present"),
                rodata_data: unsafe {
                    config
                        .map_mmap_ptr(2)
                        .expect("BPF map `rodata` does not have mmap pointer")
                        .cast::<types::rodata>()
                        .as_mut()
                        .expect("BPF map `rodata` mmap pointer is NULL")
                },
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct SslsnoopMaps<'obj> {
        pub events: libbpf_rs::MapMut<'obj>,
        pub ssl_buffers: libbpf_rs::MapMut<'obj>,
        pub rodata: libbpf_rs::MapMut<'obj>,
        pub rodata_data: &'obj types::rodata,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> SslsnoopMaps<'obj> {
        #[allow(unused_variables)]
        unsafe fn new(
            config: &libbpf_rs::__internal_skel::ObjectSkeletonConfig<'_>,
            object: &mut libbpf_rs::Object,
        ) -> libbpf_rs::Result<Self> {
            let mut events = None;
            let mut ssl_buffers = None;
            let mut rodata = None;
            let object = unsafe {
                std::mem::transmute::<&mut libbpf_rs::Object, &'obj mut libbpf_rs::Object>(object)
            };
            #[allow(clippy::never_loop)]
            for map in object.maps_mut() {
                let name = map.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "map has invalid name",
                    ))
                })?;
                #[allow(clippy::match_single_binding)]
                match name {
                    "events" => events = Some(map),
                    "ssl_buffers" => ssl_buffers = Some(map),
                    "sslsnoop.rodata" => rodata = Some(map),
                    _ => panic!("encountered unexpected map: `{name}`"),
                }
            }

            let slf = Self {
                events: events.expect("map `events` not present"),
                ssl_buffers: ssl_buffers.expect("map `ssl_buffers` not present"),
                rodata: rodata.expect("map `rodata` not present"),
                rodata_data: unsafe {
                    config
                        .map_mmap_ptr(2)
                        .expect("BPF map `rodata` does not have mmap pointer")
                        .cast::<types::rodata>()
                        .as_ref()
                        .expect("BPF map `rodata` mmap pointer is NULL")
                },
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct OpenSslsnoopProgs<'obj> {
        pub probe_func: libbpf_rs::OpenProgramMut<'obj>,
        pub retprobe_read: libbpf_rs::OpenProgramMut<'obj>,
        pub retprobe_write: libbpf_rs::OpenProgramMut<'obj>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> OpenSslsnoopProgs<'obj> {
        unsafe fn new(object: &mut libbpf_rs::OpenObject) -> libbpf_rs::Result<Self> {
            let mut probe_func = None;
            let mut retprobe_read = None;
            let mut retprobe_write = None;
            let object = unsafe {
                std::mem::transmute::<&mut libbpf_rs::OpenObject, &'obj mut libbpf_rs::OpenObject>(
                    object,
                )
            };
            for prog in object.progs_mut() {
                let name = prog.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "prog has invalid name",
                    ))
                })?;
                match name {
                    "probe_func" => probe_func = Some(prog),
                    "retprobe_read" => retprobe_read = Some(prog),
                    "retprobe_write" => retprobe_write = Some(prog),
                    _ => panic!("encountered unexpected prog: `{name}`"),
                }
            }

            let slf = Self {
                probe_func: probe_func.expect("prog `probe_func` not present"),
                retprobe_read: retprobe_read.expect("prog `retprobe_read` not present"),
                retprobe_write: retprobe_write.expect("prog `retprobe_write` not present"),
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct SslsnoopProgs<'obj> {
        pub probe_func: libbpf_rs::ProgramMut<'obj>,
        pub retprobe_read: libbpf_rs::ProgramMut<'obj>,
        pub retprobe_write: libbpf_rs::ProgramMut<'obj>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> SslsnoopProgs<'obj> {
        #[allow(unused_variables)]
        fn new(open_progs: OpenSslsnoopProgs<'obj>) -> Self {
            Self {
                probe_func: unsafe {
                    libbpf_rs::ProgramMut::new_mut(
                        open_progs.probe_func.as_libbpf_object().as_mut(),
                    )
                },
                retprobe_read: unsafe {
                    libbpf_rs::ProgramMut::new_mut(
                        open_progs.retprobe_read.as_libbpf_object().as_mut(),
                    )
                },
                retprobe_write: unsafe {
                    libbpf_rs::ProgramMut::new_mut(
                        open_progs.retprobe_write.as_libbpf_object().as_mut(),
                    )
                },
                _phantom: std::marker::PhantomData,
            }
        }
    }
    struct OwnedRef<'obj, O> {
        object: Option<&'obj mut std::mem::MaybeUninit<O>>,
    }

    impl<'obj, O> OwnedRef<'obj, O> {
        /// # Safety
        /// The object has to be initialized.
        unsafe fn new(object: &'obj mut std::mem::MaybeUninit<O>) -> Self {
            Self {
                object: Some(object),
            }
        }

        fn as_ref(&self) -> &O {
            // SAFETY: As per the contract during construction, the
            //         object has to be initialized.
            unsafe { self.object.as_ref().unwrap().assume_init_ref() }
        }

        fn as_mut(&mut self) -> &mut O {
            // SAFETY: As per the contract during construction, the
            //         object has to be initialized.
            unsafe { self.object.as_mut().unwrap().assume_init_mut() }
        }

        fn take(mut self) -> &'obj mut std::mem::MaybeUninit<O> {
            self.object.take().unwrap()
        }
    }

    impl<O> Drop for OwnedRef<'_, O> {
        fn drop(&mut self) {
            if let Some(object) = &mut self.object {
                unsafe { object.assume_init_drop() }
            }
        }
    }

    #[derive(Default)]
    pub struct SslsnoopSkelBuilder {
        pub obj_builder: libbpf_rs::ObjectBuilder,
    }

    impl<'obj> SslsnoopSkelBuilder {
        fn open_opts_impl(
            self,
            open_opts: *const libbpf_sys::bpf_object_open_opts,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenSslsnoopSkel<'obj>> {
            let skel_config = build_skel_config()?;
            let skel_ptr = skel_config.as_libbpf_object();

            let ret =
                unsafe { libbpf_sys::bpf_object__open_skeleton(skel_ptr.as_ptr(), open_opts) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            // SAFETY: `skel_ptr` points to a valid object after the
            //         open call.
            let obj_ptr = unsafe { *skel_ptr.as_ref().obj };
            // SANITY: `bpf_object__open_skeleton` should have
            //         allocated the object.
            let obj_ptr = std::ptr::NonNull::new(obj_ptr).unwrap();
            // SAFETY: `obj_ptr` points to an opened object after
            //         skeleton open.
            let obj = unsafe { libbpf_rs::OpenObject::from_ptr(obj_ptr) };
            let _obj = object.write(obj);
            // SAFETY: We just wrote initialized data to `object`.
            let mut obj_ref = unsafe { OwnedRef::new(object) };

            #[allow(unused_mut)]
            let mut skel = OpenSslsnoopSkel {
                maps: unsafe { OpenSslsnoopMaps::new(&skel_config, obj_ref.as_mut())? },
                progs: unsafe { OpenSslsnoopProgs::new(obj_ref.as_mut())? },
                obj: obj_ref,
                // SAFETY: Our `struct_ops` type contains only pointers,
                //         which are allowed to be NULL.
                // TODO: Generate and use a `Default` representation
                //       instead, to cut down on unsafe code.
                struct_ops: unsafe { std::mem::zeroed() },
                skel_config,
            };

            Ok(skel)
        }
    }

    impl<'obj> SkelBuilder<'obj> for SslsnoopSkelBuilder {
        type Output = OpenSslsnoopSkel<'obj>;
        fn open(
            self,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenSslsnoopSkel<'obj>> {
            self.open_opts_impl(std::ptr::null(), object)
        }

        fn open_opts(
            self,
            open_opts: libbpf_sys::bpf_object_open_opts,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenSslsnoopSkel<'obj>> {
            self.open_opts_impl(&open_opts, object)
        }

        fn object_builder(&self) -> &libbpf_rs::ObjectBuilder {
            &self.obj_builder
        }
        fn object_builder_mut(&mut self) -> &mut libbpf_rs::ObjectBuilder {
            &mut self.obj_builder
        }
    }

    #[derive(Debug, Clone)]
    #[repr(C)]
    pub struct StructOps {}

    impl StructOps {}
    pub mod types {
        #[allow(unused_imports)]
        use super::*;
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct __anon_1 {
            pub r#type: *mut [i32; 27],
            pub max_entries: *mut [i32; 131072],
        }
        impl Default for __anon_1 {
            fn default() -> Self {
                Self {
                    r#type: std::ptr::null_mut(),
                    max_entries: std::ptr::null_mut(),
                }
            }
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct __anon_2 {
            pub r#type: *mut [i32; 1],
            pub key: *mut u64,
            pub value: *mut *mut *mut i8,
            pub max_entries: *mut [i32; 102400],
        }
        impl Default for __anon_2 {
            fn default() -> Self {
                Self {
                    r#type: std::ptr::null_mut(),
                    key: std::ptr::null_mut(),
                    value: std::ptr::null_mut(),
                    max_entries: std::ptr::null_mut(),
                }
            }
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct pt_regs {
            pub r15: u64,
            pub r14: u64,
            pub r13: u64,
            pub r12: u64,
            pub bp: u64,
            pub bx: u64,
            pub r11: u64,
            pub r10: u64,
            pub r9: u64,
            pub r8: u64,
            pub ax: u64,
            pub cx: u64,
            pub dx: u64,
            pub si: u64,
            pub di: u64,
            pub orig_ax: u64,
            pub ip: u64,
            pub cs: u64,
            pub flags: u64,
            pub sp: u64,
            pub ss: u64,
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct event {
            pub pid_tgid: u64,
            pub len: i32,
            pub is_read: std::mem::MaybeUninit<bool>,
            pub comm: [u8; 16],
            pub data: [u8; 4096],
        }
        impl Default for event {
            fn default() -> Self {
                Self {
                    pid_tgid: u64::default(),
                    len: i32::default(),
                    is_read: std::mem::MaybeUninit::new(bool::default()),
                    comm: [u8::default(); 16],
                    data: [u8::default(); 4096],
                }
            }
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct rodata {
            pub _e: event,
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct license {
            pub LICENSE: [i8; 4],
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct maps {
            pub events: __anon_1,
            pub ssl_buffers: __anon_2,
        }
    }
    pub struct OpenSslsnoopSkel<'obj> {
        obj: OwnedRef<'obj, libbpf_rs::OpenObject>,
        pub maps: OpenSslsnoopMaps<'obj>,
        pub progs: OpenSslsnoopProgs<'obj>,
        pub struct_ops: StructOps,
        skel_config: libbpf_rs::__internal_skel::ObjectSkeletonConfig<'obj>,
    }

    impl<'obj> OpenSkel<'obj> for OpenSslsnoopSkel<'obj> {
        type Output = SslsnoopSkel<'obj>;
        fn load(self) -> libbpf_rs::Result<SslsnoopSkel<'obj>> {
            let skel_ptr = self.skel_config.as_libbpf_object().as_ptr();

            let ret = unsafe { libbpf_sys::bpf_object__load_skeleton(skel_ptr) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            let obj_ref = self.obj.take();
            let open_obj = std::mem::replace(obj_ref, std::mem::MaybeUninit::uninit());
            // SAFETY: `open_obj` is guaranteed to be properly
            //         initialized as it came from an `OwnedRef`.
            let obj_ptr = unsafe { open_obj.assume_init().take_ptr() };
            // SAFETY: `obj_ptr` points to a loaded object after
            //         skeleton load.
            let obj = unsafe { libbpf_rs::Object::from_ptr(obj_ptr) };
            // SAFETY: `OpenObject` and `Object` are guaranteed to
            //         have the same memory layout.
            let obj_ref = unsafe {
                std::mem::transmute::<
                    &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
                    &'obj mut std::mem::MaybeUninit<libbpf_rs::Object>,
                >(obj_ref)
            };
            let _obj = obj_ref.write(obj);
            // SAFETY: We just wrote initialized data to `obj_ref`.
            let mut obj_ref = unsafe { OwnedRef::new(obj_ref) };

            Ok(SslsnoopSkel {
                maps: unsafe { SslsnoopMaps::new(&self.skel_config, obj_ref.as_mut())? },
                progs: SslsnoopProgs::new(self.progs),
                obj: obj_ref,
                struct_ops: self.struct_ops,
                skel_config: self.skel_config,
                links: SslsnoopLinks::default(),
            })
        }

        fn open_object(&self) -> &libbpf_rs::OpenObject {
            self.obj.as_ref()
        }

        fn open_object_mut(&mut self) -> &mut libbpf_rs::OpenObject {
            self.obj.as_mut()
        }
    }
    #[derive(Default)]
    pub struct SslsnoopLinks {
        pub probe_func: Option<libbpf_rs::Link>,
        pub retprobe_read: Option<libbpf_rs::Link>,
        pub retprobe_write: Option<libbpf_rs::Link>,
    }
    pub struct SslsnoopSkel<'obj> {
        obj: OwnedRef<'obj, libbpf_rs::Object>,
        pub maps: SslsnoopMaps<'obj>,
        pub progs: SslsnoopProgs<'obj>,
        struct_ops: StructOps,
        skel_config: libbpf_rs::__internal_skel::ObjectSkeletonConfig<'obj>,
        pub links: SslsnoopLinks,
    }

    unsafe impl Send for SslsnoopSkel<'_> {}
    unsafe impl Sync for SslsnoopSkel<'_> {}

    impl<'obj> Skel<'obj> for SslsnoopSkel<'obj> {
        fn object(&self) -> &libbpf_rs::Object {
            self.obj.as_ref()
        }

        fn object_mut(&mut self) -> &mut libbpf_rs::Object {
            self.obj.as_mut()
        }
        fn attach(&mut self) -> libbpf_rs::Result<()> {
            let skel_ptr = self.skel_config.as_libbpf_object().as_ptr();
            let ret = unsafe { libbpf_sys::bpf_object__attach_skeleton(skel_ptr) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            self.links = SslsnoopLinks {
                probe_func: core::ptr::NonNull::new(self.skel_config.prog_link_ptr(0)?)
                    .map(|ptr| unsafe { libbpf_rs::Link::from_ptr(ptr) }),
                retprobe_read: core::ptr::NonNull::new(self.skel_config.prog_link_ptr(1)?)
                    .map(|ptr| unsafe { libbpf_rs::Link::from_ptr(ptr) }),
                retprobe_write: core::ptr::NonNull::new(self.skel_config.prog_link_ptr(2)?)
                    .map(|ptr| unsafe { libbpf_rs::Link::from_ptr(ptr) }),
            };

            Ok(())
        }
    }
    impl SslsnoopSkel<'_> {
        pub fn struct_ops_raw(&self) -> *const StructOps {
            &self.struct_ops
        }

        pub fn struct_ops(&self) -> &StructOps {
            &self.struct_ops
        }
    }
    const DATA: &[u8] = &[
        127, 69, 76, 70, 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 247, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 120, 36, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0,
        0, 64, 0, 12, 0, 1, 0, 0, 46, 115, 116, 114, 116, 97, 98, 0, 46, 115, 121, 109, 116, 97,
        98, 0, 117, 112, 114, 111, 98, 101, 47, 47, 117, 115, 114, 47, 108, 105, 98, 54, 52, 47,
        108, 105, 98, 110, 115, 112, 114, 52, 46, 115, 111, 58, 80, 82, 95, 82, 101, 97, 100, 0,
        117, 114, 101, 116, 112, 114, 111, 98, 101, 47, 47, 117, 115, 114, 47, 108, 105, 98, 54,
        52, 47, 108, 105, 98, 110, 115, 112, 114, 52, 46, 115, 111, 58, 80, 82, 95, 82, 101, 97,
        100, 0, 46, 114, 111, 100, 97, 116, 97, 0, 108, 105, 99, 101, 110, 115, 101, 0, 46, 109,
        97, 112, 115, 0, 115, 115, 108, 115, 110, 111, 111, 112, 46, 98, 112, 102, 46, 99, 0, 112,
        114, 111, 98, 101, 95, 102, 117, 110, 99, 0, 115, 115, 108, 95, 98, 117, 102, 102, 101,
        114, 115, 0, 114, 101, 116, 112, 114, 111, 98, 101, 95, 114, 101, 97, 100, 0, 101, 118,
        101, 110, 116, 115, 0, 114, 101, 116, 112, 114, 111, 98, 101, 95, 119, 114, 105, 116, 101,
        0, 95, 101, 0, 76, 73, 67, 69, 78, 83, 69, 0, 46, 114, 101, 108, 117, 112, 114, 111, 98,
        101, 47, 47, 117, 115, 114, 47, 108, 105, 98, 54, 52, 47, 108, 105, 98, 110, 115, 112, 114,
        52, 46, 115, 111, 58, 80, 82, 95, 82, 101, 97, 100, 0, 46, 114, 101, 108, 117, 114, 101,
        116, 112, 114, 111, 98, 101, 47, 47, 117, 115, 114, 47, 108, 105, 98, 54, 52, 47, 108, 105,
        98, 110, 115, 112, 114, 52, 46, 115, 111, 58, 80, 82, 95, 82, 101, 97, 100, 0, 46, 66, 84,
        70, 0, 46, 66, 84, 70, 46, 101, 120, 116, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 118, 0, 0, 0, 4, 0, 241, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 3, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 18, 0,
        3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 112, 0, 0, 0, 0, 0, 0, 0, 144, 0, 0, 0, 17, 0, 7, 0, 16, 0,
        0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 156, 0, 0, 0, 18, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 168, 1, 0, 0, 0, 0, 0, 0, 170, 0, 0, 0, 17, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0,
        0, 0, 0, 0, 0, 177, 0, 0, 0, 18, 0, 4, 0, 168, 1, 0, 0, 0, 0, 0, 0, 168, 1, 0, 0, 0, 0, 0,
        0, 192, 0, 0, 0, 17, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32, 16, 0, 0, 0, 0, 0, 0, 195, 0, 0,
        0, 17, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 121, 17, 104, 0, 0, 0, 0,
        0, 123, 26, 248, 255, 0, 0, 0, 0, 133, 0, 0, 0, 14, 0, 0, 0, 123, 10, 240, 255, 0, 0, 0, 0,
        191, 162, 0, 0, 0, 0, 0, 0, 7, 2, 0, 0, 240, 255, 255, 255, 191, 163, 0, 0, 0, 0, 0, 0, 7,
        3, 0, 0, 248, 255, 255, 255, 24, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 183, 4, 0, 0,
        0, 0, 0, 0, 133, 0, 0, 0, 2, 0, 0, 0, 183, 0, 0, 0, 0, 0, 0, 0, 149, 0, 0, 0, 0, 0, 0, 0,
        121, 24, 80, 0, 0, 0, 0, 0, 191, 129, 0, 0, 0, 0, 0, 0, 103, 1, 0, 0, 32, 0, 0, 0, 199, 1,
        0, 0, 32, 0, 0, 0, 183, 2, 0, 0, 1, 0, 0, 0, 109, 18, 45, 0, 0, 0, 0, 0, 133, 0, 0, 0, 14,
        0, 0, 0, 123, 10, 248, 255, 0, 0, 0, 0, 191, 162, 0, 0, 0, 0, 0, 0, 7, 2, 0, 0, 248, 255,
        255, 255, 24, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 1, 0, 0, 0, 191,
        6, 0, 0, 0, 0, 0, 0, 21, 6, 36, 0, 0, 0, 0, 0, 24, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 183, 2, 0, 0, 32, 16, 0, 0, 183, 3, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 131, 0, 0, 0,
        191, 7, 0, 0, 0, 0, 0, 0, 21, 7, 29, 0, 0, 0, 0, 0, 191, 113, 0, 0, 0, 0, 0, 0, 7, 1, 0, 0,
        13, 0, 0, 0, 183, 2, 0, 0, 16, 0, 0, 0, 133, 0, 0, 0, 16, 0, 0, 0, 191, 129, 0, 0, 0, 0, 0,
        0, 103, 1, 0, 0, 32, 0, 0, 0, 119, 1, 0, 0, 32, 0, 0, 0, 191, 130, 0, 0, 0, 0, 0, 0, 87, 2,
        0, 0, 255, 15, 0, 0, 183, 3, 0, 0, 0, 16, 0, 0, 45, 19, 1, 0, 0, 0, 0, 0, 183, 2, 0, 0, 0,
        16, 0, 0, 121, 161, 248, 255, 0, 0, 0, 0, 123, 23, 0, 0, 0, 0, 0, 0, 99, 135, 8, 0, 0, 0,
        0, 0, 183, 1, 0, 0, 1, 0, 0, 0, 115, 23, 12, 0, 0, 0, 0, 0, 121, 99, 0, 0, 0, 0, 0, 0, 191,
        113, 0, 0, 0, 0, 0, 0, 7, 1, 0, 0, 29, 0, 0, 0, 133, 0, 0, 0, 112, 0, 0, 0, 191, 113, 0, 0,
        0, 0, 0, 0, 183, 2, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 132, 0, 0, 0, 191, 162, 0, 0, 0, 0, 0,
        0, 7, 2, 0, 0, 248, 255, 255, 255, 24, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 133, 0,
        0, 0, 3, 0, 0, 0, 183, 0, 0, 0, 0, 0, 0, 0, 149, 0, 0, 0, 0, 0, 0, 0, 121, 24, 80, 0, 0, 0,
        0, 0, 191, 129, 0, 0, 0, 0, 0, 0, 103, 1, 0, 0, 32, 0, 0, 0, 199, 1, 0, 0, 32, 0, 0, 0,
        183, 2, 0, 0, 1, 0, 0, 0, 109, 18, 45, 0, 0, 0, 0, 0, 133, 0, 0, 0, 14, 0, 0, 0, 123, 10,
        248, 255, 0, 0, 0, 0, 191, 162, 0, 0, 0, 0, 0, 0, 7, 2, 0, 0, 248, 255, 255, 255, 24, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 1, 0, 0, 0, 191, 6, 0, 0, 0, 0, 0, 0,
        21, 6, 36, 0, 0, 0, 0, 0, 24, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 183, 2, 0, 0,
        32, 16, 0, 0, 183, 3, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 131, 0, 0, 0, 191, 7, 0, 0, 0, 0, 0,
        0, 21, 7, 29, 0, 0, 0, 0, 0, 191, 113, 0, 0, 0, 0, 0, 0, 7, 1, 0, 0, 13, 0, 0, 0, 183, 2,
        0, 0, 16, 0, 0, 0, 133, 0, 0, 0, 16, 0, 0, 0, 191, 129, 0, 0, 0, 0, 0, 0, 103, 1, 0, 0, 32,
        0, 0, 0, 119, 1, 0, 0, 32, 0, 0, 0, 191, 130, 0, 0, 0, 0, 0, 0, 87, 2, 0, 0, 255, 15, 0, 0,
        183, 3, 0, 0, 0, 16, 0, 0, 45, 19, 1, 0, 0, 0, 0, 0, 183, 2, 0, 0, 0, 16, 0, 0, 121, 161,
        248, 255, 0, 0, 0, 0, 123, 23, 0, 0, 0, 0, 0, 0, 99, 135, 8, 0, 0, 0, 0, 0, 183, 1, 0, 0,
        0, 0, 0, 0, 115, 23, 12, 0, 0, 0, 0, 0, 121, 99, 0, 0, 0, 0, 0, 0, 191, 113, 0, 0, 0, 0, 0,
        0, 7, 1, 0, 0, 29, 0, 0, 0, 133, 0, 0, 0, 112, 0, 0, 0, 191, 113, 0, 0, 0, 0, 0, 0, 183, 2,
        0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 132, 0, 0, 0, 191, 162, 0, 0, 0, 0, 0, 0, 7, 2, 0, 0, 248,
        255, 255, 255, 24, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 3, 0, 0, 0,
        183, 0, 0, 0, 0, 0, 0, 0, 149, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 71, 80, 76, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 5, 0, 0, 0, 80, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        5, 0, 0, 0, 120, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 7, 0, 0, 0, 128, 1, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 5, 0, 0, 0, 248, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 5, 0, 0, 0, 32, 2, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 7, 0, 0, 0, 40, 3, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 5, 0, 0, 0, 159, 235, 1,
        0, 24, 0, 0, 0, 0, 0, 0, 0, 84, 4, 0, 0, 84, 4, 0, 0, 84, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2,
        3, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 4, 0, 0, 0, 32, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0,
        0, 0, 2, 0, 0, 0, 4, 0, 0, 0, 27, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 1, 4, 0, 0, 0, 32, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 2, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 2, 0, 0, 0, 4, 0,
        0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 4, 16, 0, 0, 0, 25, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        30, 0, 0, 0, 5, 0, 0, 0, 64, 0, 0, 0, 42, 0, 0, 0, 0, 0, 0, 14, 7, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 2, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 2, 0, 0, 0, 4, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 12, 0, 0, 0, 49, 0, 0, 0, 0, 0, 0, 8, 13, 0, 0, 0,
        53, 0, 0, 0, 0, 0, 0, 8, 14, 0, 0, 0, 59, 0, 0, 0, 0, 0, 0, 1, 8, 0, 0, 0, 64, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 2, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 17, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        2, 18, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 19, 0, 0, 0, 78, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
        8, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 21, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 2, 0,
        0, 0, 4, 0, 0, 0, 0, 144, 1, 0, 0, 0, 0, 0, 4, 0, 0, 4, 32, 0, 0, 0, 25, 0, 0, 0, 9, 0, 0,
        0, 0, 0, 0, 0, 83, 0, 0, 0, 11, 0, 0, 0, 64, 0, 0, 0, 87, 0, 0, 0, 15, 0, 0, 0, 128, 0, 0,
        0, 30, 0, 0, 0, 20, 0, 0, 0, 192, 0, 0, 0, 93, 0, 0, 0, 0, 0, 0, 14, 22, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 2, 25, 0, 0, 0, 105, 0, 0, 0, 21, 0, 0, 4, 168, 0, 0, 0, 113, 0, 0,
        0, 26, 0, 0, 0, 0, 0, 0, 0, 117, 0, 0, 0, 26, 0, 0, 0, 64, 0, 0, 0, 121, 0, 0, 0, 26, 0, 0,
        0, 128, 0, 0, 0, 125, 0, 0, 0, 26, 0, 0, 0, 192, 0, 0, 0, 129, 0, 0, 0, 26, 0, 0, 0, 0, 1,
        0, 0, 132, 0, 0, 0, 26, 0, 0, 0, 64, 1, 0, 0, 135, 0, 0, 0, 26, 0, 0, 0, 128, 1, 0, 0, 139,
        0, 0, 0, 26, 0, 0, 0, 192, 1, 0, 0, 143, 0, 0, 0, 26, 0, 0, 0, 0, 2, 0, 0, 146, 0, 0, 0,
        26, 0, 0, 0, 64, 2, 0, 0, 149, 0, 0, 0, 26, 0, 0, 0, 128, 2, 0, 0, 152, 0, 0, 0, 26, 0, 0,
        0, 192, 2, 0, 0, 155, 0, 0, 0, 26, 0, 0, 0, 0, 3, 0, 0, 158, 0, 0, 0, 26, 0, 0, 0, 64, 3,
        0, 0, 161, 0, 0, 0, 26, 0, 0, 0, 128, 3, 0, 0, 164, 0, 0, 0, 26, 0, 0, 0, 192, 3, 0, 0,
        172, 0, 0, 0, 26, 0, 0, 0, 0, 4, 0, 0, 175, 0, 0, 0, 26, 0, 0, 0, 64, 4, 0, 0, 178, 0, 0,
        0, 26, 0, 0, 0, 128, 4, 0, 0, 184, 0, 0, 0, 26, 0, 0, 0, 192, 4, 0, 0, 187, 0, 0, 0, 26, 0,
        0, 0, 0, 5, 0, 0, 190, 0, 0, 0, 0, 0, 0, 1, 8, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        13, 2, 0, 0, 0, 204, 0, 0, 0, 24, 0, 0, 0, 208, 0, 0, 0, 1, 0, 0, 12, 27, 0, 0, 0, 219, 0,
        0, 0, 1, 0, 0, 12, 27, 0, 0, 0, 233, 0, 0, 0, 1, 0, 0, 12, 27, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 10, 32, 0, 0, 0, 248, 0, 0, 0, 5, 0, 0, 4, 32, 16, 0, 0, 254, 0, 0, 0, 12, 0, 0, 0, 0,
        0, 0, 0, 7, 1, 0, 0, 2, 0, 0, 0, 64, 0, 0, 0, 11, 1, 0, 0, 33, 0, 0, 0, 96, 0, 0, 0, 19, 1,
        0, 0, 38, 0, 0, 0, 104, 0, 0, 0, 24, 1, 0, 0, 39, 0, 0, 0, 232, 0, 0, 0, 29, 1, 0, 0, 0, 0,
        0, 8, 34, 0, 0, 0, 34, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 8, 0, 0, 4, 40, 1, 0, 0, 0, 0, 0,
        8, 36, 0, 0, 0, 43, 1, 0, 0, 0, 0, 0, 8, 37, 0, 0, 0, 48, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
        8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 35, 0, 0, 0, 4, 0, 0, 0, 16, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 35, 0, 0, 0, 4, 0, 0, 0, 0, 16, 0, 0, 62, 1, 0, 0, 0, 0, 0,
        14, 31, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 19, 0, 0, 0, 4, 0, 0, 0,
        4, 0, 0, 0, 65, 1, 0, 0, 0, 0, 0, 14, 41, 0, 0, 0, 1, 0, 0, 0, 239, 4, 0, 0, 1, 0, 0, 15,
        32, 16, 0, 0, 40, 0, 0, 0, 0, 0, 0, 0, 32, 16, 0, 0, 247, 4, 0, 0, 1, 0, 0, 15, 4, 0, 0, 0,
        42, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 255, 4, 0, 0, 2, 0, 0, 15, 48, 0, 0, 0, 8, 0, 0, 0, 0,
        0, 0, 0, 16, 0, 0, 0, 23, 0, 0, 0, 16, 0, 0, 0, 32, 0, 0, 0, 0, 105, 110, 116, 0, 95, 95,
        65, 82, 82, 65, 89, 95, 83, 73, 90, 69, 95, 84, 89, 80, 69, 95, 95, 0, 116, 121, 112, 101,
        0, 109, 97, 120, 95, 101, 110, 116, 114, 105, 101, 115, 0, 101, 118, 101, 110, 116, 115, 0,
        117, 54, 52, 0, 95, 95, 117, 54, 52, 0, 117, 110, 115, 105, 103, 110, 101, 100, 32, 108,
        111, 110, 103, 32, 108, 111, 110, 103, 0, 99, 104, 97, 114, 0, 107, 101, 121, 0, 118, 97,
        108, 117, 101, 0, 115, 115, 108, 95, 98, 117, 102, 102, 101, 114, 115, 0, 112, 116, 95,
        114, 101, 103, 115, 0, 114, 49, 53, 0, 114, 49, 52, 0, 114, 49, 51, 0, 114, 49, 50, 0, 98,
        112, 0, 98, 120, 0, 114, 49, 49, 0, 114, 49, 48, 0, 114, 57, 0, 114, 56, 0, 97, 120, 0, 99,
        120, 0, 100, 120, 0, 115, 105, 0, 100, 105, 0, 111, 114, 105, 103, 95, 97, 120, 0, 105,
        112, 0, 99, 115, 0, 102, 108, 97, 103, 115, 0, 115, 112, 0, 115, 115, 0, 117, 110, 115,
        105, 103, 110, 101, 100, 32, 108, 111, 110, 103, 0, 99, 116, 120, 0, 112, 114, 111, 98,
        101, 95, 102, 117, 110, 99, 0, 114, 101, 116, 112, 114, 111, 98, 101, 95, 114, 101, 97,
        100, 0, 114, 101, 116, 112, 114, 111, 98, 101, 95, 119, 114, 105, 116, 101, 0, 101, 118,
        101, 110, 116, 0, 112, 105, 100, 95, 116, 103, 105, 100, 0, 108, 101, 110, 0, 105, 115, 95,
        114, 101, 97, 100, 0, 99, 111, 109, 109, 0, 100, 97, 116, 97, 0, 98, 111, 111, 108, 0, 95,
        66, 111, 111, 108, 0, 117, 56, 0, 95, 95, 117, 56, 0, 117, 110, 115, 105, 103, 110, 101,
        100, 32, 99, 104, 97, 114, 0, 95, 101, 0, 76, 73, 67, 69, 78, 83, 69, 0, 47, 104, 111, 109,
        101, 47, 122, 104, 117, 108, 105, 47, 100, 97, 116, 97, 47, 108, 105, 98, 98, 112, 102, 45,
        116, 111, 111, 108, 115, 45, 114, 115, 47, 115, 115, 108, 115, 110, 111, 111, 112, 47, 115,
        114, 99, 47, 98, 112, 102, 47, 115, 115, 108, 115, 110, 111, 111, 112, 46, 98, 112, 102,
        46, 99, 0, 105, 110, 116, 32, 66, 80, 70, 95, 75, 80, 82, 79, 66, 69, 40, 112, 114, 111,
        98, 101, 95, 102, 117, 110, 99, 44, 32, 118, 111, 105, 100, 32, 42, 115, 44, 32, 99, 111,
        110, 115, 116, 32, 99, 104, 97, 114, 32, 42, 98, 117, 102, 44, 32, 105, 110, 116, 32, 110,
        117, 109, 41, 32, 123, 0, 32, 32, 117, 54, 52, 32, 112, 105, 100, 95, 116, 103, 105, 100,
        32, 61, 32, 98, 112, 102, 95, 103, 101, 116, 95, 99, 117, 114, 114, 101, 110, 116, 95, 112,
        105, 100, 95, 116, 103, 105, 100, 40, 41, 59, 0, 32, 32, 98, 112, 102, 95, 109, 97, 112,
        95, 117, 112, 100, 97, 116, 101, 95, 101, 108, 101, 109, 40, 38, 115, 115, 108, 95, 98,
        117, 102, 102, 101, 114, 115, 44, 32, 38, 112, 105, 100, 95, 116, 103, 105, 100, 44, 32,
        38, 98, 117, 102, 44, 32, 48, 41, 59, 0, 105, 110, 116, 32, 66, 80, 70, 95, 75, 82, 69, 84,
        80, 82, 79, 66, 69, 40, 114, 101, 116, 112, 114, 111, 98, 101, 95, 114, 101, 97, 100, 44,
        32, 105, 110, 116, 32, 114, 101, 116, 118, 97, 108, 41, 32, 123, 32, 114, 101, 116, 117,
        114, 110, 32, 111, 117, 116, 112, 117, 116, 40, 114, 101, 116, 118, 97, 108, 44, 32, 116,
        114, 117, 101, 41, 59, 32, 125, 0, 32, 32, 105, 102, 32, 40, 108, 101, 110, 32, 60, 61, 32,
        48, 41, 0, 32, 32, 99, 111, 110, 115, 116, 32, 99, 104, 97, 114, 32, 42, 42, 98, 117, 102,
        32, 61, 32, 98, 112, 102, 95, 109, 97, 112, 95, 108, 111, 111, 107, 117, 112, 95, 101, 108,
        101, 109, 40, 38, 115, 115, 108, 95, 98, 117, 102, 102, 101, 114, 115, 44, 32, 38, 112,
        105, 100, 95, 116, 103, 105, 100, 41, 59, 0, 32, 32, 105, 102, 32, 40, 98, 117, 102, 32,
        61, 61, 32, 78, 85, 76, 76, 41, 32, 123, 0, 32, 32, 115, 116, 114, 117, 99, 116, 32, 101,
        118, 101, 110, 116, 32, 42, 101, 118, 101, 110, 116, 32, 61, 32, 98, 112, 102, 95, 114,
        105, 110, 103, 98, 117, 102, 95, 114, 101, 115, 101, 114, 118, 101, 40, 38, 101, 118, 101,
        110, 116, 115, 44, 32, 115, 105, 122, 101, 111, 102, 40, 115, 116, 114, 117, 99, 116, 32,
        101, 118, 101, 110, 116, 41, 44, 32, 48, 41, 59, 0, 32, 32, 105, 102, 32, 40, 101, 118,
        101, 110, 116, 32, 61, 61, 32, 78, 85, 76, 76, 41, 32, 123, 0, 32, 32, 98, 112, 102, 95,
        103, 101, 116, 95, 99, 117, 114, 114, 101, 110, 116, 95, 99, 111, 109, 109, 40, 101, 118,
        101, 110, 116, 45, 62, 99, 111, 109, 109, 44, 32, 67, 79, 77, 77, 95, 77, 65, 88, 95, 76,
        69, 78, 41, 59, 0, 32, 32, 108, 101, 110, 32, 61, 32, 40, 108, 101, 110, 32, 62, 61, 32,
        68, 65, 84, 65, 95, 77, 65, 88, 95, 76, 69, 78, 32, 63, 32, 68, 65, 84, 65, 95, 77, 65, 88,
        95, 76, 69, 78, 32, 58, 32, 108, 101, 110, 32, 38, 32, 40, 68, 65, 84, 65, 95, 77, 65, 88,
        95, 76, 69, 78, 32, 45, 32, 49, 41, 41, 59, 0, 32, 32, 101, 118, 101, 110, 116, 45, 62,
        112, 105, 100, 95, 116, 103, 105, 100, 32, 61, 32, 112, 105, 100, 95, 116, 103, 105, 100,
        59, 0, 32, 32, 101, 118, 101, 110, 116, 45, 62, 108, 101, 110, 32, 61, 32, 108, 101, 110,
        59, 0, 32, 32, 101, 118, 101, 110, 116, 45, 62, 105, 115, 95, 114, 101, 97, 100, 32, 61,
        32, 105, 115, 95, 114, 101, 97, 100, 59, 0, 32, 32, 98, 112, 102, 95, 112, 114, 111, 98,
        101, 95, 114, 101, 97, 100, 95, 117, 115, 101, 114, 40, 101, 118, 101, 110, 116, 45, 62,
        100, 97, 116, 97, 44, 32, 108, 101, 110, 44, 32, 42, 98, 117, 102, 41, 59, 0, 32, 32, 98,
        112, 102, 95, 114, 105, 110, 103, 98, 117, 102, 95, 115, 117, 98, 109, 105, 116, 40, 101,
        118, 101, 110, 116, 44, 32, 48, 41, 59, 0, 32, 32, 98, 112, 102, 95, 109, 97, 112, 95, 100,
        101, 108, 101, 116, 101, 95, 101, 108, 101, 109, 40, 38, 115, 115, 108, 95, 98, 117, 102,
        102, 101, 114, 115, 44, 32, 38, 112, 105, 100, 95, 116, 103, 105, 100, 41, 59, 0, 105, 110,
        116, 32, 66, 80, 70, 95, 75, 82, 69, 84, 80, 82, 79, 66, 69, 40, 114, 101, 116, 112, 114,
        111, 98, 101, 95, 119, 114, 105, 116, 101, 44, 32, 105, 110, 116, 32, 114, 101, 116, 118,
        97, 108, 41, 32, 123, 32, 114, 101, 116, 117, 114, 110, 32, 111, 117, 116, 112, 117, 116,
        40, 114, 101, 116, 118, 97, 108, 44, 32, 102, 97, 108, 115, 101, 41, 59, 32, 125, 0, 48,
        58, 49, 51, 0, 48, 58, 49, 48, 0, 46, 114, 111, 100, 97, 116, 97, 0, 108, 105, 99, 101,
        110, 115, 101, 0, 46, 109, 97, 112, 115, 0, 117, 112, 114, 111, 98, 101, 47, 47, 117, 115,
        114, 47, 108, 105, 98, 54, 52, 47, 108, 105, 98, 110, 115, 112, 114, 52, 46, 115, 111, 58,
        80, 82, 95, 82, 101, 97, 100, 0, 117, 114, 101, 116, 112, 114, 111, 98, 101, 47, 47, 117,
        115, 114, 47, 108, 105, 98, 54, 52, 47, 108, 105, 98, 110, 115, 112, 114, 52, 46, 115, 111,
        58, 80, 82, 95, 82, 101, 97, 100, 0, 159, 235, 1, 0, 32, 0, 0, 0, 0, 0, 0, 0, 44, 0, 0, 0,
        44, 0, 0, 0, 36, 3, 0, 0, 80, 3, 0, 0, 68, 0, 0, 0, 8, 0, 0, 0, 5, 5, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 28, 0, 0, 0, 43, 5, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 29, 0, 0, 0, 168, 1, 0, 0, 30,
        0, 0, 0, 16, 0, 0, 0, 5, 5, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 73, 1, 0, 0, 138, 1, 0, 0, 5,
        244, 0, 0, 16, 0, 0, 0, 73, 1, 0, 0, 202, 1, 0, 0, 18, 128, 0, 0, 24, 0, 0, 0, 73, 1, 0, 0,
        202, 1, 0, 0, 7, 128, 0, 0, 64, 0, 0, 0, 73, 1, 0, 0, 247, 1, 0, 0, 3, 132, 0, 0, 96, 0, 0,
        0, 73, 1, 0, 0, 138, 1, 0, 0, 5, 244, 0, 0, 43, 5, 0, 0, 44, 0, 0, 0, 0, 0, 0, 0, 73, 1, 0,
        0, 48, 2, 0, 0, 5, 8, 1, 0, 40, 0, 0, 0, 73, 1, 0, 0, 126, 2, 0, 0, 7, 152, 0, 0, 48, 0, 0,
        0, 73, 1, 0, 0, 202, 1, 0, 0, 18, 160, 0, 0, 56, 0, 0, 0, 73, 1, 0, 0, 202, 1, 0, 0, 7,
        160, 0, 0, 80, 0, 0, 0, 73, 1, 0, 0, 142, 2, 0, 0, 22, 164, 0, 0, 112, 0, 0, 0, 73, 1, 0,
        0, 209, 2, 0, 0, 7, 168, 0, 0, 120, 0, 0, 0, 73, 1, 0, 0, 230, 2, 0, 0, 25, 180, 0, 0, 168,
        0, 0, 0, 73, 1, 0, 0, 53, 3, 0, 0, 7, 184, 0, 0, 176, 0, 0, 0, 73, 1, 0, 0, 76, 3, 0, 0,
        31, 196, 0, 0, 192, 0, 0, 0, 73, 1, 0, 0, 76, 3, 0, 0, 3, 196, 0, 0, 208, 0, 0, 0, 73, 1,
        0, 0, 48, 2, 0, 0, 5, 8, 1, 0, 232, 0, 0, 0, 73, 1, 0, 0, 127, 3, 0, 0, 10, 212, 0, 0, 16,
        1, 0, 0, 73, 1, 0, 0, 200, 3, 0, 0, 21, 200, 0, 0, 24, 1, 0, 0, 73, 1, 0, 0, 200, 3, 0, 0,
        19, 200, 0, 0, 32, 1, 0, 0, 73, 1, 0, 0, 230, 3, 0, 0, 14, 208, 0, 0, 48, 1, 0, 0, 73, 1,
        0, 0, 250, 3, 0, 0, 18, 204, 0, 0, 56, 1, 0, 0, 73, 1, 0, 0, 22, 4, 0, 0, 41, 216, 0, 0,
        64, 1, 0, 0, 73, 1, 0, 0, 22, 4, 0, 0, 30, 216, 0, 0, 80, 1, 0, 0, 73, 1, 0, 0, 22, 4, 0,
        0, 3, 216, 0, 0, 88, 1, 0, 0, 73, 1, 0, 0, 69, 4, 0, 0, 3, 220, 0, 0, 128, 1, 0, 0, 73, 1,
        0, 0, 101, 4, 0, 0, 3, 224, 0, 0, 152, 1, 0, 0, 73, 1, 0, 0, 48, 2, 0, 0, 5, 8, 1, 0, 168,
        1, 0, 0, 73, 1, 0, 0, 149, 4, 0, 0, 5, 20, 1, 0, 208, 1, 0, 0, 73, 1, 0, 0, 126, 2, 0, 0,
        7, 152, 0, 0, 216, 1, 0, 0, 73, 1, 0, 0, 202, 1, 0, 0, 18, 160, 0, 0, 224, 1, 0, 0, 73, 1,
        0, 0, 202, 1, 0, 0, 7, 160, 0, 0, 248, 1, 0, 0, 73, 1, 0, 0, 142, 2, 0, 0, 22, 164, 0, 0,
        24, 2, 0, 0, 73, 1, 0, 0, 209, 2, 0, 0, 7, 168, 0, 0, 32, 2, 0, 0, 73, 1, 0, 0, 230, 2, 0,
        0, 25, 180, 0, 0, 80, 2, 0, 0, 73, 1, 0, 0, 53, 3, 0, 0, 7, 184, 0, 0, 88, 2, 0, 0, 73, 1,
        0, 0, 76, 3, 0, 0, 31, 196, 0, 0, 104, 2, 0, 0, 73, 1, 0, 0, 76, 3, 0, 0, 3, 196, 0, 0,
        120, 2, 0, 0, 73, 1, 0, 0, 149, 4, 0, 0, 5, 20, 1, 0, 144, 2, 0, 0, 73, 1, 0, 0, 127, 3, 0,
        0, 10, 212, 0, 0, 184, 2, 0, 0, 73, 1, 0, 0, 200, 3, 0, 0, 21, 200, 0, 0, 192, 2, 0, 0, 73,
        1, 0, 0, 200, 3, 0, 0, 19, 200, 0, 0, 200, 2, 0, 0, 73, 1, 0, 0, 230, 3, 0, 0, 14, 208, 0,
        0, 216, 2, 0, 0, 73, 1, 0, 0, 250, 3, 0, 0, 18, 204, 0, 0, 224, 2, 0, 0, 73, 1, 0, 0, 22,
        4, 0, 0, 41, 216, 0, 0, 232, 2, 0, 0, 73, 1, 0, 0, 22, 4, 0, 0, 30, 216, 0, 0, 248, 2, 0,
        0, 73, 1, 0, 0, 22, 4, 0, 0, 3, 216, 0, 0, 0, 3, 0, 0, 73, 1, 0, 0, 69, 4, 0, 0, 3, 220, 0,
        0, 40, 3, 0, 0, 73, 1, 0, 0, 101, 4, 0, 0, 3, 224, 0, 0, 64, 3, 0, 0, 73, 1, 0, 0, 149, 4,
        0, 0, 5, 20, 1, 0, 16, 0, 0, 0, 5, 5, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 25, 0, 0, 0, 229, 4, 0,
        0, 0, 0, 0, 0, 43, 5, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 25, 0, 0, 0, 234, 4, 0, 0, 0, 0, 0, 0,
        168, 1, 0, 0, 25, 0, 0, 0, 234, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 3,
        0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 48, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        9, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 112, 1, 0, 0, 0, 0,
        0, 0, 8, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 24, 0, 0, 0,
        0, 0, 0, 0, 17, 0, 0, 0, 1, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 120,
        2, 0, 0, 0, 0, 0, 0, 112, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 55, 0, 0, 0, 1, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 232, 2, 0, 0, 0, 0, 0, 0, 80, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 96, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 56, 6, 0, 0, 0, 0, 0, 0, 32, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 104, 0, 0, 0, 1, 0, 0, 0, 3, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 88, 22, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 112, 0, 0, 0, 1, 0, 0,
        0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 96, 22, 0, 0, 0, 0, 0, 0, 48, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 203, 0,
        0, 0, 9, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 144, 22, 0, 0, 0, 0, 0,
        0, 16, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0,
        0, 0, 0, 245, 0, 0, 0, 9, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 160,
        22, 0, 0, 0, 0, 0, 0, 96, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 4, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0,
        0, 16, 0, 0, 0, 0, 0, 0, 0, 34, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 23, 0, 0, 0, 0, 0, 0, 192, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 39, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 192, 32, 0, 0, 0, 0, 0, 0, 180, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    ];
}
