// SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause)
//
// THIS FILE IS AUTOGENERATED BY CARGO-LIBBPF-GEN!

pub use self::imp::*;

#[allow(dead_code)]
#[allow(non_snake_case)]
#[allow(non_camel_case_types)]
#[allow(clippy::absolute_paths)]
#[allow(clippy::upper_case_acronyms)]
#[allow(clippy::zero_repeat_side_effects)]
#[warn(single_use_lifetimes)]
mod imp {
    #[allow(unused_imports)]
    use super::*;
    use libbpf_rs::libbpf_sys;
    use libbpf_rs::skel::OpenSkel;
    use libbpf_rs::skel::Skel;
    use libbpf_rs::skel::SkelBuilder;
    use libbpf_rs::AsRawLibbpf as _;
    use libbpf_rs::MapCore as _;
    fn build_skel_config(
    ) -> libbpf_rs::Result<libbpf_rs::__internal_skel::ObjectSkeletonConfig<'static>> {
        let mut builder = libbpf_rs::__internal_skel::ObjectSkeletonConfigBuilder::new(DATA);
        builder
            .name("opensnoop_bpf")
            .map("start", false)
            .map("events", false)
            .map("opensnoo.rodata", true)
            .prog("tracepoint__syscalls__sys_enter_open")
            .prog("tracepoint__syscalls__sys_enter_openat")
            .prog("tracepoint__syscalls__sys_exit_open")
            .prog("tracepoint__syscalls__sys_exit_openat");
        builder.build()
    }
    pub struct OpenOpensnoopMaps<'obj> {
        pub start: libbpf_rs::OpenMapMut<'obj>,
        pub events: libbpf_rs::OpenMapMut<'obj>,
        pub rodata: libbpf_rs::OpenMapMut<'obj>,
        pub rodata_data: &'obj mut types::rodata,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> OpenOpensnoopMaps<'obj> {
        #[allow(unused_variables)]
        unsafe fn new(
            config: &libbpf_rs::__internal_skel::ObjectSkeletonConfig<'_>,
            object: &mut libbpf_rs::OpenObject,
        ) -> libbpf_rs::Result<Self> {
            let mut start = None;
            let mut events = None;
            let mut rodata = None;
            let object = unsafe {
                std::mem::transmute::<&mut libbpf_rs::OpenObject, &'obj mut libbpf_rs::OpenObject>(
                    object,
                )
            };
            #[allow(clippy::never_loop)]
            for map in object.maps_mut() {
                let name = map.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "map has invalid name",
                    ))
                })?;
                #[allow(clippy::match_single_binding)]
                match name {
                    "start" => start = Some(map),
                    "events" => events = Some(map),
                    "opensnoo.rodata" => rodata = Some(map),
                    _ => panic!("encountered unexpected map: `{name}`"),
                }
            }

            let slf = Self {
                start: start.expect("map `start` not present"),
                events: events.expect("map `events` not present"),
                rodata: rodata.expect("map `rodata` not present"),
                rodata_data: unsafe {
                    config
                        .map_mmap_ptr(2)
                        .expect("BPF map `rodata` does not have mmap pointer")
                        .cast::<types::rodata>()
                        .as_mut()
                        .expect("BPF map `rodata` mmap pointer is NULL")
                },
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct OpensnoopMaps<'obj> {
        pub start: libbpf_rs::MapMut<'obj>,
        pub events: libbpf_rs::MapMut<'obj>,
        pub rodata: libbpf_rs::MapMut<'obj>,
        pub rodata_data: &'obj types::rodata,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> OpensnoopMaps<'obj> {
        #[allow(unused_variables)]
        unsafe fn new(
            config: &libbpf_rs::__internal_skel::ObjectSkeletonConfig<'_>,
            object: &mut libbpf_rs::Object,
        ) -> libbpf_rs::Result<Self> {
            let mut start = None;
            let mut events = None;
            let mut rodata = None;
            let object = unsafe {
                std::mem::transmute::<&mut libbpf_rs::Object, &'obj mut libbpf_rs::Object>(object)
            };
            #[allow(clippy::never_loop)]
            for map in object.maps_mut() {
                let name = map.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "map has invalid name",
                    ))
                })?;
                #[allow(clippy::match_single_binding)]
                match name {
                    "start" => start = Some(map),
                    "events" => events = Some(map),
                    "opensnoo.rodata" => rodata = Some(map),
                    _ => panic!("encountered unexpected map: `{name}`"),
                }
            }

            let slf = Self {
                start: start.expect("map `start` not present"),
                events: events.expect("map `events` not present"),
                rodata: rodata.expect("map `rodata` not present"),
                rodata_data: unsafe {
                    config
                        .map_mmap_ptr(2)
                        .expect("BPF map `rodata` does not have mmap pointer")
                        .cast::<types::rodata>()
                        .as_ref()
                        .expect("BPF map `rodata` mmap pointer is NULL")
                },
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct OpenOpensnoopProgs<'obj> {
        pub tracepoint__syscalls__sys_enter_open: libbpf_rs::OpenProgramMut<'obj>,
        pub tracepoint__syscalls__sys_enter_openat: libbpf_rs::OpenProgramMut<'obj>,
        pub tracepoint__syscalls__sys_exit_open: libbpf_rs::OpenProgramMut<'obj>,
        pub tracepoint__syscalls__sys_exit_openat: libbpf_rs::OpenProgramMut<'obj>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> OpenOpensnoopProgs<'obj> {
        unsafe fn new(object: &mut libbpf_rs::OpenObject) -> libbpf_rs::Result<Self> {
            let mut tracepoint__syscalls__sys_enter_open = None;
            let mut tracepoint__syscalls__sys_enter_openat = None;
            let mut tracepoint__syscalls__sys_exit_open = None;
            let mut tracepoint__syscalls__sys_exit_openat = None;
            let object = unsafe {
                std::mem::transmute::<&mut libbpf_rs::OpenObject, &'obj mut libbpf_rs::OpenObject>(
                    object,
                )
            };
            for prog in object.progs_mut() {
                let name = prog.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "prog has invalid name",
                    ))
                })?;
                match name {
                    "tracepoint__syscalls__sys_enter_open" => {
                        tracepoint__syscalls__sys_enter_open = Some(prog)
                    }
                    "tracepoint__syscalls__sys_enter_openat" => {
                        tracepoint__syscalls__sys_enter_openat = Some(prog)
                    }
                    "tracepoint__syscalls__sys_exit_open" => {
                        tracepoint__syscalls__sys_exit_open = Some(prog)
                    }
                    "tracepoint__syscalls__sys_exit_openat" => {
                        tracepoint__syscalls__sys_exit_openat = Some(prog)
                    }
                    _ => panic!("encountered unexpected prog: `{name}`"),
                }
            }

            let slf = Self {
                tracepoint__syscalls__sys_enter_open: tracepoint__syscalls__sys_enter_open
                    .expect("prog `tracepoint__syscalls__sys_enter_open` not present"),
                tracepoint__syscalls__sys_enter_openat: tracepoint__syscalls__sys_enter_openat
                    .expect("prog `tracepoint__syscalls__sys_enter_openat` not present"),
                tracepoint__syscalls__sys_exit_open: tracepoint__syscalls__sys_exit_open
                    .expect("prog `tracepoint__syscalls__sys_exit_open` not present"),
                tracepoint__syscalls__sys_exit_openat: tracepoint__syscalls__sys_exit_openat
                    .expect("prog `tracepoint__syscalls__sys_exit_openat` not present"),
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct OpensnoopProgs<'obj> {
        pub tracepoint__syscalls__sys_enter_open: libbpf_rs::ProgramMut<'obj>,
        pub tracepoint__syscalls__sys_enter_openat: libbpf_rs::ProgramMut<'obj>,
        pub tracepoint__syscalls__sys_exit_open: libbpf_rs::ProgramMut<'obj>,
        pub tracepoint__syscalls__sys_exit_openat: libbpf_rs::ProgramMut<'obj>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> OpensnoopProgs<'obj> {
        #[allow(unused_variables)]
        fn new(open_progs: OpenOpensnoopProgs<'obj>) -> Self {
            Self {
                tracepoint__syscalls__sys_enter_open: unsafe {
                    libbpf_rs::ProgramMut::new_mut(
                        open_progs
                            .tracepoint__syscalls__sys_enter_open
                            .as_libbpf_object()
                            .as_mut(),
                    )
                },
                tracepoint__syscalls__sys_enter_openat: unsafe {
                    libbpf_rs::ProgramMut::new_mut(
                        open_progs
                            .tracepoint__syscalls__sys_enter_openat
                            .as_libbpf_object()
                            .as_mut(),
                    )
                },
                tracepoint__syscalls__sys_exit_open: unsafe {
                    libbpf_rs::ProgramMut::new_mut(
                        open_progs
                            .tracepoint__syscalls__sys_exit_open
                            .as_libbpf_object()
                            .as_mut(),
                    )
                },
                tracepoint__syscalls__sys_exit_openat: unsafe {
                    libbpf_rs::ProgramMut::new_mut(
                        open_progs
                            .tracepoint__syscalls__sys_exit_openat
                            .as_libbpf_object()
                            .as_mut(),
                    )
                },
                _phantom: std::marker::PhantomData,
            }
        }
    }
    struct OwnedRef<'obj, O> {
        object: Option<&'obj mut std::mem::MaybeUninit<O>>,
    }

    impl<'obj, O> OwnedRef<'obj, O> {
        /// # Safety
        /// The object has to be initialized.
        unsafe fn new(object: &'obj mut std::mem::MaybeUninit<O>) -> Self {
            Self {
                object: Some(object),
            }
        }

        fn as_ref(&self) -> &O {
            // SAFETY: As per the contract during construction, the
            //         object has to be initialized.
            unsafe { self.object.as_ref().unwrap().assume_init_ref() }
        }

        fn as_mut(&mut self) -> &mut O {
            // SAFETY: As per the contract during construction, the
            //         object has to be initialized.
            unsafe { self.object.as_mut().unwrap().assume_init_mut() }
        }

        fn take(mut self) -> &'obj mut std::mem::MaybeUninit<O> {
            self.object.take().unwrap()
        }
    }

    impl<O> Drop for OwnedRef<'_, O> {
        fn drop(&mut self) {
            if let Some(object) = &mut self.object {
                unsafe { object.assume_init_drop() }
            }
        }
    }

    #[derive(Default)]
    pub struct OpensnoopSkelBuilder {
        pub obj_builder: libbpf_rs::ObjectBuilder,
    }

    impl<'obj> OpensnoopSkelBuilder {
        fn open_opts_impl(
            self,
            open_opts: *const libbpf_sys::bpf_object_open_opts,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenOpensnoopSkel<'obj>> {
            let skel_config = build_skel_config()?;
            let skel_ptr = skel_config.as_libbpf_object();

            let ret =
                unsafe { libbpf_sys::bpf_object__open_skeleton(skel_ptr.as_ptr(), open_opts) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            // SAFETY: `skel_ptr` points to a valid object after the
            //         open call.
            let obj_ptr = unsafe { *skel_ptr.as_ref().obj };
            // SANITY: `bpf_object__open_skeleton` should have
            //         allocated the object.
            let obj_ptr = std::ptr::NonNull::new(obj_ptr).unwrap();
            // SAFETY: `obj_ptr` points to an opened object after
            //         skeleton open.
            let obj = unsafe { libbpf_rs::OpenObject::from_ptr(obj_ptr) };
            let _obj = object.write(obj);
            // SAFETY: We just wrote initialized data to `object`.
            let mut obj_ref = unsafe { OwnedRef::new(object) };

            #[allow(unused_mut)]
            let mut skel = OpenOpensnoopSkel {
                maps: unsafe { OpenOpensnoopMaps::new(&skel_config, obj_ref.as_mut())? },
                progs: unsafe { OpenOpensnoopProgs::new(obj_ref.as_mut())? },
                obj: obj_ref,
                // SAFETY: Our `struct_ops` type contains only pointers,
                //         which are allowed to be NULL.
                // TODO: Generate and use a `Default` representation
                //       instead, to cut down on unsafe code.
                struct_ops: unsafe { std::mem::zeroed() },
                skel_config,
            };

            Ok(skel)
        }
    }

    impl<'obj> SkelBuilder<'obj> for OpensnoopSkelBuilder {
        type Output = OpenOpensnoopSkel<'obj>;
        fn open(
            self,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenOpensnoopSkel<'obj>> {
            self.open_opts_impl(std::ptr::null(), object)
        }

        fn open_opts(
            self,
            open_opts: libbpf_sys::bpf_object_open_opts,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenOpensnoopSkel<'obj>> {
            self.open_opts_impl(&open_opts, object)
        }

        fn object_builder(&self) -> &libbpf_rs::ObjectBuilder {
            &self.obj_builder
        }
        fn object_builder_mut(&mut self) -> &mut libbpf_rs::ObjectBuilder {
            &mut self.obj_builder
        }
    }

    #[derive(Debug, Clone)]
    #[repr(C)]
    pub struct StructOps {}

    impl StructOps {}
    pub mod types {
        #[allow(unused_imports)]
        use super::*;
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct args_t {
            pub fname: *mut i8,
            pub flags: i32,
            pub __pad_12: [u8; 4],
        }
        impl Default for args_t {
            fn default() -> Self {
                Self {
                    fname: std::ptr::null_mut(),
                    flags: i32::default(),
                    __pad_12: [u8::default(); 4],
                }
            }
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct __anon_1 {
            pub r#type: *mut [i32; 1],
            pub max_entries: *mut [i32; 10240],
            pub key: *mut u32,
            pub value: *mut args_t,
        }
        impl Default for __anon_1 {
            fn default() -> Self {
                Self {
                    r#type: std::ptr::null_mut(),
                    max_entries: std::ptr::null_mut(),
                    key: std::ptr::null_mut(),
                    value: std::ptr::null_mut(),
                }
            }
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct __anon_2 {
            pub r#type: *mut [i32; 27],
            pub max_entries: *mut [i32; 10000],
        }
        impl Default for __anon_2 {
            fn default() -> Self {
                Self {
                    r#type: std::ptr::null_mut(),
                    max_entries: std::ptr::null_mut(),
                }
            }
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct trace_event_raw_sys_enter {
            pub ent: trace_entry,
            pub id: i64,
            pub args: [u64; 6],
            pub __data: [i8; 0],
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct trace_entry {
            pub r#type: u16,
            pub flags: u8,
            pub preempt_count: u8,
            pub pid: i32,
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct trace_event_raw_sys_exit {
            pub ent: trace_entry,
            pub id: i64,
            pub ret: i64,
            pub __data: [i8; 0],
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct event {
            pub ts: u64,
            pub pid: i32,
            pub uid: u32,
            pub ret: i32,
            pub flags: i32,
            pub callers: [u64; 2],
            pub comm: [u8; 16],
            pub fname: [u8; 255],
        }
        impl Default for event {
            fn default() -> Self {
                Self {
                    ts: u64::default(),
                    pid: i32::default(),
                    uid: u32::default(),
                    ret: i32::default(),
                    flags: i32::default(),
                    callers: [u64::default(); 2],
                    comm: [u8::default(); 16],
                    fname: [u8::default(); 255],
                }
            }
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct rodata {
            pub targ_pid: i32,
            pub targ_tgid: i32,
            pub targ_uid: u32,
            pub targ_failed: bool,
            pub _event: event,
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct maps {
            pub start: __anon_1,
            pub events: __anon_2,
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct license {
            pub LICENSE: [i8; 4],
        }
    }
    pub struct OpenOpensnoopSkel<'obj> {
        obj: OwnedRef<'obj, libbpf_rs::OpenObject>,
        pub maps: OpenOpensnoopMaps<'obj>,
        pub progs: OpenOpensnoopProgs<'obj>,
        pub struct_ops: StructOps,
        skel_config: libbpf_rs::__internal_skel::ObjectSkeletonConfig<'obj>,
    }

    impl<'obj> OpenSkel<'obj> for OpenOpensnoopSkel<'obj> {
        type Output = OpensnoopSkel<'obj>;
        fn load(self) -> libbpf_rs::Result<OpensnoopSkel<'obj>> {
            let skel_ptr = self.skel_config.as_libbpf_object().as_ptr();

            let ret = unsafe { libbpf_sys::bpf_object__load_skeleton(skel_ptr) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            let obj_ref = self.obj.take();
            let open_obj = std::mem::replace(obj_ref, std::mem::MaybeUninit::uninit());
            // SAFETY: `open_obj` is guaranteed to be properly
            //         initialized as it came from an `OwnedRef`.
            let obj_ptr = unsafe { open_obj.assume_init().take_ptr() };
            // SAFETY: `obj_ptr` points to a loaded object after
            //         skeleton load.
            let obj = unsafe { libbpf_rs::Object::from_ptr(obj_ptr) };
            // SAFETY: `OpenObject` and `Object` are guaranteed to
            //         have the same memory layout.
            let obj_ref = unsafe {
                std::mem::transmute::<
                    &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
                    &'obj mut std::mem::MaybeUninit<libbpf_rs::Object>,
                >(obj_ref)
            };
            let _obj = obj_ref.write(obj);
            // SAFETY: We just wrote initialized data to `obj_ref`.
            let mut obj_ref = unsafe { OwnedRef::new(obj_ref) };

            Ok(OpensnoopSkel {
                maps: unsafe { OpensnoopMaps::new(&self.skel_config, obj_ref.as_mut())? },
                progs: OpensnoopProgs::new(self.progs),
                obj: obj_ref,
                struct_ops: self.struct_ops,
                skel_config: self.skel_config,
                links: OpensnoopLinks::default(),
            })
        }

        fn open_object(&self) -> &libbpf_rs::OpenObject {
            self.obj.as_ref()
        }

        fn open_object_mut(&mut self) -> &mut libbpf_rs::OpenObject {
            self.obj.as_mut()
        }
    }
    #[derive(Default)]
    pub struct OpensnoopLinks {
        pub tracepoint__syscalls__sys_enter_open: Option<libbpf_rs::Link>,
        pub tracepoint__syscalls__sys_enter_openat: Option<libbpf_rs::Link>,
        pub tracepoint__syscalls__sys_exit_open: Option<libbpf_rs::Link>,
        pub tracepoint__syscalls__sys_exit_openat: Option<libbpf_rs::Link>,
    }
    pub struct OpensnoopSkel<'obj> {
        obj: OwnedRef<'obj, libbpf_rs::Object>,
        pub maps: OpensnoopMaps<'obj>,
        pub progs: OpensnoopProgs<'obj>,
        struct_ops: StructOps,
        skel_config: libbpf_rs::__internal_skel::ObjectSkeletonConfig<'obj>,
        pub links: OpensnoopLinks,
    }

    unsafe impl Send for OpensnoopSkel<'_> {}
    unsafe impl Sync for OpensnoopSkel<'_> {}

    impl<'obj> Skel<'obj> for OpensnoopSkel<'obj> {
        fn object(&self) -> &libbpf_rs::Object {
            self.obj.as_ref()
        }

        fn object_mut(&mut self) -> &mut libbpf_rs::Object {
            self.obj.as_mut()
        }
        fn attach(&mut self) -> libbpf_rs::Result<()> {
            let skel_ptr = self.skel_config.as_libbpf_object().as_ptr();
            let ret = unsafe { libbpf_sys::bpf_object__attach_skeleton(skel_ptr) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            self.links = OpensnoopLinks {
                tracepoint__syscalls__sys_enter_open: core::ptr::NonNull::new(
                    self.skel_config.prog_link_ptr(0)?,
                )
                .map(|ptr| unsafe { libbpf_rs::Link::from_ptr(ptr) }),
                tracepoint__syscalls__sys_enter_openat: core::ptr::NonNull::new(
                    self.skel_config.prog_link_ptr(1)?,
                )
                .map(|ptr| unsafe { libbpf_rs::Link::from_ptr(ptr) }),
                tracepoint__syscalls__sys_exit_open: core::ptr::NonNull::new(
                    self.skel_config.prog_link_ptr(2)?,
                )
                .map(|ptr| unsafe { libbpf_rs::Link::from_ptr(ptr) }),
                tracepoint__syscalls__sys_exit_openat: core::ptr::NonNull::new(
                    self.skel_config.prog_link_ptr(3)?,
                )
                .map(|ptr| unsafe { libbpf_rs::Link::from_ptr(ptr) }),
            };

            Ok(())
        }
    }
    impl OpensnoopSkel<'_> {
        pub fn struct_ops_raw(&self) -> *const StructOps {
            &self.struct_ops
        }

        pub fn struct_ops(&self) -> &StructOps {
            &self.struct_ops
        }
    }
    const DATA: &[u8] = &[
        127, 69, 76, 70, 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 247, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 160, 36, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0,
        0, 64, 0, 16, 0, 1, 0, 0, 46, 115, 116, 114, 116, 97, 98, 0, 46, 115, 121, 109, 116, 97,
        98, 0, 116, 114, 97, 99, 101, 112, 111, 105, 110, 116, 47, 115, 121, 115, 99, 97, 108, 108,
        115, 47, 115, 121, 115, 95, 101, 110, 116, 101, 114, 95, 111, 112, 101, 110, 0, 116, 114,
        97, 99, 101, 112, 111, 105, 110, 116, 47, 115, 121, 115, 99, 97, 108, 108, 115, 47, 115,
        121, 115, 95, 101, 110, 116, 101, 114, 95, 111, 112, 101, 110, 97, 116, 0, 116, 114, 97,
        99, 101, 112, 111, 105, 110, 116, 47, 115, 121, 115, 99, 97, 108, 108, 115, 47, 115, 121,
        115, 95, 101, 120, 105, 116, 95, 111, 112, 101, 110, 0, 116, 114, 97, 99, 101, 112, 111,
        105, 110, 116, 47, 115, 121, 115, 99, 97, 108, 108, 115, 47, 115, 121, 115, 95, 101, 120,
        105, 116, 95, 111, 112, 101, 110, 97, 116, 0, 46, 114, 111, 100, 97, 116, 97, 0, 46, 109,
        97, 112, 115, 0, 108, 105, 99, 101, 110, 115, 101, 0, 111, 112, 101, 110, 115, 110, 111,
        111, 112, 46, 98, 112, 102, 46, 99, 0, 116, 114, 97, 99, 101, 112, 111, 105, 110, 116, 95,
        95, 115, 121, 115, 99, 97, 108, 108, 115, 95, 95, 115, 121, 115, 95, 101, 110, 116, 101,
        114, 95, 111, 112, 101, 110, 0, 116, 97, 114, 103, 95, 116, 103, 105, 100, 0, 116, 97, 114,
        103, 95, 112, 105, 100, 0, 116, 97, 114, 103, 95, 117, 105, 100, 0, 115, 116, 97, 114, 116,
        0, 116, 114, 97, 99, 101, 112, 111, 105, 110, 116, 95, 95, 115, 121, 115, 99, 97, 108, 108,
        115, 95, 95, 115, 121, 115, 95, 101, 110, 116, 101, 114, 95, 111, 112, 101, 110, 97, 116,
        0, 116, 114, 97, 99, 101, 112, 111, 105, 110, 116, 95, 95, 115, 121, 115, 99, 97, 108, 108,
        115, 95, 95, 115, 121, 115, 95, 101, 120, 105, 116, 95, 111, 112, 101, 110, 0, 116, 97,
        114, 103, 95, 102, 97, 105, 108, 101, 100, 0, 101, 118, 101, 110, 116, 115, 0, 116, 114,
        97, 99, 101, 112, 111, 105, 110, 116, 95, 95, 115, 121, 115, 99, 97, 108, 108, 115, 95, 95,
        115, 121, 115, 95, 101, 120, 105, 116, 95, 111, 112, 101, 110, 97, 116, 0, 95, 101, 118,
        101, 110, 116, 0, 76, 73, 67, 69, 78, 83, 69, 0, 46, 114, 101, 108, 116, 114, 97, 99, 101,
        112, 111, 105, 110, 116, 47, 115, 121, 115, 99, 97, 108, 108, 115, 47, 115, 121, 115, 95,
        101, 110, 116, 101, 114, 95, 111, 112, 101, 110, 0, 46, 114, 101, 108, 116, 114, 97, 99,
        101, 112, 111, 105, 110, 116, 47, 115, 121, 115, 99, 97, 108, 108, 115, 47, 115, 121, 115,
        95, 101, 110, 116, 101, 114, 95, 111, 112, 101, 110, 97, 116, 0, 46, 114, 101, 108, 116,
        114, 97, 99, 101, 112, 111, 105, 110, 116, 47, 115, 121, 115, 99, 97, 108, 108, 115, 47,
        115, 121, 115, 95, 101, 120, 105, 116, 95, 111, 112, 101, 110, 0, 46, 114, 101, 108, 116,
        114, 97, 99, 101, 112, 111, 105, 110, 116, 47, 115, 121, 115, 99, 97, 108, 108, 115, 47,
        115, 121, 115, 95, 101, 120, 105, 116, 95, 111, 112, 101, 110, 97, 116, 0, 46, 66, 84, 70,
        0, 46, 66, 84, 70, 46, 101, 120, 116, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 181, 0, 0, 0, 4, 0, 241, 255, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 3, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        3, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 6, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 197, 0, 0, 0, 18, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 112, 1, 0, 0, 0, 0, 0, 0, 234, 0, 0, 0, 17, 0, 7, 0, 4, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0,
        0, 0, 0, 0, 244, 0, 0, 0, 17, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 253,
        0, 0, 0, 17, 0, 7, 0, 8, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 6, 1, 0, 0, 17, 0, 8,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 12, 1, 0, 0, 18, 0, 4, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 112, 1, 0, 0, 0, 0, 0, 0, 51, 1, 0, 0, 18, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        248, 1, 0, 0, 0, 0, 0, 0, 87, 1, 0, 0, 17, 0, 7, 0, 12, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 99, 1, 0, 0, 17, 0, 8, 0, 32, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 106,
        1, 0, 0, 18, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 248, 1, 0, 0, 0, 0, 0, 0, 144, 1, 0, 0, 17,
        0, 7, 0, 16, 0, 0, 0, 0, 0, 0, 0, 56, 1, 0, 0, 0, 0, 0, 0, 151, 1, 0, 0, 17, 0, 9, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 191, 22, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 14, 0,
        0, 0, 99, 10, 252, 255, 0, 0, 0, 0, 24, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 97,
        18, 0, 0, 0, 0, 0, 0, 21, 2, 4, 0, 0, 0, 0, 0, 97, 17, 0, 0, 0, 0, 0, 0, 191, 2, 0, 0, 0,
        0, 0, 0, 119, 2, 0, 0, 32, 0, 0, 0, 93, 33, 33, 0, 0, 0, 0, 0, 24, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 97, 18, 0, 0, 0, 0, 0, 0, 21, 2, 4, 0, 0, 0, 0, 0, 97, 17, 0, 0, 0, 0,
        0, 0, 103, 0, 0, 0, 32, 0, 0, 0, 119, 0, 0, 0, 32, 0, 0, 0, 93, 1, 25, 0, 0, 0, 0, 0, 24,
        7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 97, 113, 0, 0, 0, 0, 0, 0, 24, 2, 0, 0, 255,
        255, 255, 255, 0, 0, 0, 0, 0, 0, 0, 0, 29, 33, 5, 0, 0, 0, 0, 0, 133, 0, 0, 0, 15, 0, 0, 0,
        97, 113, 0, 0, 0, 0, 0, 0, 103, 0, 0, 0, 32, 0, 0, 0, 119, 0, 0, 0, 32, 0, 0, 0, 93, 1, 14,
        0, 0, 0, 0, 0, 183, 1, 0, 0, 0, 0, 0, 0, 123, 26, 240, 255, 0, 0, 0, 0, 121, 97, 16, 0, 0,
        0, 0, 0, 123, 26, 232, 255, 0, 0, 0, 0, 121, 97, 24, 0, 0, 0, 0, 0, 99, 26, 240, 255, 0, 0,
        0, 0, 191, 162, 0, 0, 0, 0, 0, 0, 7, 2, 0, 0, 252, 255, 255, 255, 191, 163, 0, 0, 0, 0, 0,
        0, 7, 3, 0, 0, 232, 255, 255, 255, 24, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 183, 4,
        0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 2, 0, 0, 0, 183, 0, 0, 0, 0, 0, 0, 0, 149, 0, 0, 0, 0, 0,
        0, 0, 191, 22, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 14, 0, 0, 0, 99, 10, 252, 255, 0, 0, 0, 0,
        24, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 97, 18, 0, 0, 0, 0, 0, 0, 21, 2, 4, 0, 0,
        0, 0, 0, 97, 17, 0, 0, 0, 0, 0, 0, 191, 2, 0, 0, 0, 0, 0, 0, 119, 2, 0, 0, 32, 0, 0, 0, 93,
        33, 33, 0, 0, 0, 0, 0, 24, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 97, 18, 0, 0, 0, 0,
        0, 0, 21, 2, 4, 0, 0, 0, 0, 0, 97, 17, 0, 0, 0, 0, 0, 0, 103, 0, 0, 0, 32, 0, 0, 0, 119, 0,
        0, 0, 32, 0, 0, 0, 93, 1, 25, 0, 0, 0, 0, 0, 24, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 97, 113, 0, 0, 0, 0, 0, 0, 24, 2, 0, 0, 255, 255, 255, 255, 0, 0, 0, 0, 0, 0, 0, 0, 29,
        33, 5, 0, 0, 0, 0, 0, 133, 0, 0, 0, 15, 0, 0, 0, 97, 113, 0, 0, 0, 0, 0, 0, 103, 0, 0, 0,
        32, 0, 0, 0, 119, 0, 0, 0, 32, 0, 0, 0, 93, 1, 14, 0, 0, 0, 0, 0, 183, 1, 0, 0, 0, 0, 0, 0,
        123, 26, 240, 255, 0, 0, 0, 0, 121, 97, 24, 0, 0, 0, 0, 0, 123, 26, 232, 255, 0, 0, 0, 0,
        121, 97, 32, 0, 0, 0, 0, 0, 99, 26, 240, 255, 0, 0, 0, 0, 191, 162, 0, 0, 0, 0, 0, 0, 7, 2,
        0, 0, 252, 255, 255, 255, 191, 163, 0, 0, 0, 0, 0, 0, 7, 3, 0, 0, 232, 255, 255, 255, 24,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 183, 4, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 2, 0,
        0, 0, 183, 0, 0, 0, 0, 0, 0, 0, 149, 0, 0, 0, 0, 0, 0, 0, 191, 22, 0, 0, 0, 0, 0, 0, 133,
        0, 0, 0, 14, 0, 0, 0, 99, 10, 228, 255, 0, 0, 0, 0, 191, 162, 0, 0, 0, 0, 0, 0, 7, 2, 0, 0,
        228, 255, 255, 255, 24, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 1, 0, 0,
        0, 191, 7, 0, 0, 0, 0, 0, 0, 21, 7, 51, 0, 0, 0, 0, 0, 121, 105, 16, 0, 0, 0, 0, 0, 24, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 113, 17, 0, 0, 0, 0, 0, 0, 85, 1, 4, 0, 1, 0, 0,
        0, 191, 145, 0, 0, 0, 0, 0, 0, 103, 1, 0, 0, 32, 0, 0, 0, 199, 1, 0, 0, 32, 0, 0, 0, 101,
        1, 37, 0, 255, 255, 255, 255, 24, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 183, 2, 0,
        0, 56, 1, 0, 0, 183, 3, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 131, 0, 0, 0, 191, 8, 0, 0, 0, 0,
        0, 0, 21, 8, 35, 0, 0, 0, 0, 0, 133, 0, 0, 0, 14, 0, 0, 0, 119, 0, 0, 0, 32, 0, 0, 0, 99,
        8, 8, 0, 0, 0, 0, 0, 133, 0, 0, 0, 15, 0, 0, 0, 99, 8, 12, 0, 0, 0, 0, 0, 191, 129, 0, 0,
        0, 0, 0, 0, 7, 1, 0, 0, 40, 0, 0, 0, 183, 2, 0, 0, 16, 0, 0, 0, 133, 0, 0, 0, 16, 0, 0, 0,
        121, 115, 0, 0, 0, 0, 0, 0, 191, 129, 0, 0, 0, 0, 0, 0, 7, 1, 0, 0, 56, 0, 0, 0, 183, 2, 0,
        0, 255, 0, 0, 0, 133, 0, 0, 0, 114, 0, 0, 0, 97, 113, 8, 0, 0, 0, 0, 0, 99, 24, 20, 0, 0,
        0, 0, 0, 99, 152, 16, 0, 0, 0, 0, 0, 191, 162, 0, 0, 0, 0, 0, 0, 7, 2, 0, 0, 232, 255, 255,
        255, 191, 97, 0, 0, 0, 0, 0, 0, 183, 3, 0, 0, 24, 0, 0, 0, 183, 4, 0, 0, 0, 1, 0, 0, 133,
        0, 0, 0, 67, 0, 0, 0, 121, 161, 240, 255, 0, 0, 0, 0, 123, 24, 24, 0, 0, 0, 0, 0, 121, 161,
        248, 255, 0, 0, 0, 0, 123, 24, 32, 0, 0, 0, 0, 0, 191, 129, 0, 0, 0, 0, 0, 0, 183, 2, 0, 0,
        0, 0, 0, 0, 133, 0, 0, 0, 132, 0, 0, 0, 191, 162, 0, 0, 0, 0, 0, 0, 7, 2, 0, 0, 228, 255,
        255, 255, 24, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 3, 0, 0, 0, 183,
        0, 0, 0, 0, 0, 0, 0, 149, 0, 0, 0, 0, 0, 0, 0, 191, 22, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 14,
        0, 0, 0, 99, 10, 228, 255, 0, 0, 0, 0, 191, 162, 0, 0, 0, 0, 0, 0, 7, 2, 0, 0, 228, 255,
        255, 255, 24, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 1, 0, 0, 0, 191,
        7, 0, 0, 0, 0, 0, 0, 21, 7, 51, 0, 0, 0, 0, 0, 121, 105, 16, 0, 0, 0, 0, 0, 24, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 113, 17, 0, 0, 0, 0, 0, 0, 85, 1, 4, 0, 1, 0, 0, 0, 191,
        145, 0, 0, 0, 0, 0, 0, 103, 1, 0, 0, 32, 0, 0, 0, 199, 1, 0, 0, 32, 0, 0, 0, 101, 1, 37, 0,
        255, 255, 255, 255, 24, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 183, 2, 0, 0, 56, 1,
        0, 0, 183, 3, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 131, 0, 0, 0, 191, 8, 0, 0, 0, 0, 0, 0, 21,
        8, 35, 0, 0, 0, 0, 0, 133, 0, 0, 0, 14, 0, 0, 0, 119, 0, 0, 0, 32, 0, 0, 0, 99, 8, 8, 0, 0,
        0, 0, 0, 133, 0, 0, 0, 15, 0, 0, 0, 99, 8, 12, 0, 0, 0, 0, 0, 191, 129, 0, 0, 0, 0, 0, 0,
        7, 1, 0, 0, 40, 0, 0, 0, 183, 2, 0, 0, 16, 0, 0, 0, 133, 0, 0, 0, 16, 0, 0, 0, 121, 115, 0,
        0, 0, 0, 0, 0, 191, 129, 0, 0, 0, 0, 0, 0, 7, 1, 0, 0, 56, 0, 0, 0, 183, 2, 0, 0, 255, 0,
        0, 0, 133, 0, 0, 0, 114, 0, 0, 0, 97, 113, 8, 0, 0, 0, 0, 0, 99, 24, 20, 0, 0, 0, 0, 0, 99,
        152, 16, 0, 0, 0, 0, 0, 191, 162, 0, 0, 0, 0, 0, 0, 7, 2, 0, 0, 232, 255, 255, 255, 191,
        97, 0, 0, 0, 0, 0, 0, 183, 3, 0, 0, 24, 0, 0, 0, 183, 4, 0, 0, 0, 1, 0, 0, 133, 0, 0, 0,
        67, 0, 0, 0, 121, 161, 240, 255, 0, 0, 0, 0, 123, 24, 24, 0, 0, 0, 0, 0, 121, 161, 248,
        255, 0, 0, 0, 0, 123, 24, 32, 0, 0, 0, 0, 0, 191, 129, 0, 0, 0, 0, 0, 0, 183, 2, 0, 0, 0,
        0, 0, 0, 133, 0, 0, 0, 132, 0, 0, 0, 191, 162, 0, 0, 0, 0, 0, 0, 7, 2, 0, 0, 228, 255, 255,
        255, 24, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 3, 0, 0, 0, 183, 0, 0,
        0, 0, 0, 0, 0, 149, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 255, 255, 255, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 71, 80, 76, 0, 0, 0, 0, 0, 24, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 7, 0, 0, 0, 88, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 8, 0, 0, 0, 152, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 9, 0, 0, 0,
        64, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 10, 0, 0, 0, 24, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 7,
        0, 0, 0, 88, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 8, 0, 0, 0, 152, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 9, 0, 0, 0, 64, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 10, 0, 0, 0, 40, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 10, 0, 0, 0, 88, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 13, 0, 0, 0, 152, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 14, 0, 0, 0, 208, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 10, 0, 0, 0, 40,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 10, 0, 0, 0, 88, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 13, 0,
        0, 0, 152, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 14, 0, 0, 0, 208, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 10, 0, 0, 0, 159, 235, 1, 0, 24, 0, 0, 0, 0, 0, 0, 0, 224, 5, 0, 0, 224, 5, 0, 0, 232,
        8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 3, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 4, 0, 0, 0, 32, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 2, 0, 0, 0, 4, 0, 0, 0, 1, 0, 0, 0, 5, 0, 0, 0, 0,
        0, 0, 1, 4, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        3, 0, 0, 0, 0, 2, 0, 0, 0, 4, 0, 0, 0, 0, 40, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 8, 0, 0, 0, 25,
        0, 0, 0, 0, 0, 0, 8, 9, 0, 0, 0, 29, 0, 0, 0, 0, 0, 0, 8, 10, 0, 0, 0, 35, 0, 0, 0, 0, 0,
        0, 1, 4, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 12, 0, 0, 0, 48, 0, 0, 0, 2, 0, 0,
        4, 16, 0, 0, 0, 55, 0, 0, 0, 13, 0, 0, 0, 0, 0, 0, 0, 61, 0, 0, 0, 2, 0, 0, 0, 64, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 2, 14, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 15, 0, 0, 0, 67, 0, 0, 0, 0,
        0, 0, 1, 1, 0, 0, 0, 8, 0, 0, 1, 0, 0, 0, 0, 4, 0, 0, 4, 32, 0, 0, 0, 72, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 77, 0, 0, 0, 5, 0, 0, 0, 64, 0, 0, 0, 89, 0, 0, 0, 7, 0, 0, 0, 128, 0, 0, 0,
        93, 0, 0, 0, 11, 0, 0, 0, 192, 0, 0, 0, 99, 0, 0, 0, 0, 0, 0, 14, 16, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 2, 19, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 2, 0, 0, 0, 4, 0,
        0, 0, 27, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 21, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0,
        2, 0, 0, 0, 4, 0, 0, 0, 16, 39, 0, 0, 0, 0, 0, 0, 2, 0, 0, 4, 16, 0, 0, 0, 72, 0, 0, 0, 18,
        0, 0, 0, 0, 0, 0, 0, 77, 0, 0, 0, 20, 0, 0, 0, 64, 0, 0, 0, 105, 0, 0, 0, 0, 0, 0, 14, 22,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 25, 0, 0, 0, 112, 0, 0, 0, 4, 0, 0, 4, 64, 0,
        0, 0, 138, 0, 0, 0, 26, 0, 0, 0, 0, 0, 0, 0, 142, 0, 0, 0, 29, 0, 0, 0, 64, 0, 0, 0, 145,
        0, 0, 0, 31, 0, 0, 0, 128, 0, 0, 0, 150, 0, 0, 0, 32, 0, 0, 0, 0, 2, 0, 0, 157, 0, 0, 0, 4,
        0, 0, 4, 8, 0, 0, 0, 72, 0, 0, 0, 27, 0, 0, 0, 0, 0, 0, 0, 61, 0, 0, 0, 28, 0, 0, 0, 16, 0,
        0, 0, 169, 0, 0, 0, 28, 0, 0, 0, 24, 0, 0, 0, 183, 0, 0, 0, 2, 0, 0, 0, 32, 0, 0, 0, 187,
        0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 16, 0, 0, 0, 202, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 8, 0,
        0, 0, 216, 0, 0, 0, 0, 0, 0, 1, 8, 0, 0, 0, 64, 0, 0, 1, 221, 0, 0, 0, 0, 0, 0, 1, 8, 0, 0,
        0, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 30, 0, 0, 0, 4, 0, 0, 0, 6, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 15, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        13, 2, 0, 0, 0, 235, 0, 0, 0, 24, 0, 0, 0, 239, 0, 0, 0, 1, 0, 0, 12, 33, 0, 0, 0, 20, 1,
        0, 0, 1, 0, 0, 12, 33, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 37, 0, 0, 0, 59, 1, 0, 0, 4, 0, 0,
        4, 24, 0, 0, 0, 138, 0, 0, 0, 26, 0, 0, 0, 0, 0, 0, 0, 142, 0, 0, 0, 29, 0, 0, 0, 64, 0, 0,
        0, 84, 1, 0, 0, 29, 0, 0, 0, 128, 0, 0, 0, 150, 0, 0, 0, 32, 0, 0, 0, 192, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 13, 2, 0, 0, 0, 235, 0, 0, 0, 36, 0, 0, 0, 88, 1, 0, 0, 1, 0, 0, 12, 38, 0,
        0, 0, 124, 1, 0, 0, 1, 0, 0, 12, 38, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 42, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 9, 43, 0, 0, 0, 162, 1, 0, 0, 0, 0, 0, 8, 44, 0, 0, 0, 168, 1, 0, 0, 0, 0,
        0, 8, 2, 0, 0, 0, 183, 1, 0, 0, 0, 0, 0, 14, 41, 0, 0, 0, 1, 0, 0, 0, 192, 1, 0, 0, 0, 0,
        0, 14, 41, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 48, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        9, 49, 0, 0, 0, 202, 1, 0, 0, 0, 0, 0, 8, 50, 0, 0, 0, 208, 1, 0, 0, 0, 0, 0, 8, 10, 0, 0,
        0, 225, 1, 0, 0, 0, 0, 0, 14, 47, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 53, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 9, 54, 0, 0, 0, 234, 1, 0, 0, 0, 0, 0, 8, 55, 0, 0, 0, 239, 1, 0,
        0, 0, 0, 0, 1, 1, 0, 0, 0, 8, 0, 0, 4, 245, 1, 0, 0, 0, 0, 0, 14, 52, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 10, 58, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 59, 0, 0, 0, 1, 2, 0, 0, 8,
        0, 0, 4, 56, 1, 0, 0, 7, 2, 0, 0, 60, 0, 0, 0, 0, 0, 0, 0, 183, 0, 0, 0, 43, 0, 0, 0, 64,
        0, 0, 0, 10, 2, 0, 0, 49, 0, 0, 0, 96, 0, 0, 0, 84, 1, 0, 0, 2, 0, 0, 0, 128, 0, 0, 0, 61,
        0, 0, 0, 2, 0, 0, 0, 160, 0, 0, 0, 14, 2, 0, 0, 62, 0, 0, 0, 192, 0, 0, 0, 22, 2, 0, 0, 65,
        0, 0, 0, 64, 1, 0, 0, 55, 0, 0, 0, 66, 0, 0, 0, 192, 1, 0, 0, 27, 2, 0, 0, 0, 0, 0, 8, 61,
        0, 0, 0, 33, 2, 0, 0, 0, 0, 0, 1, 8, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0,
        0, 60, 0, 0, 0, 4, 0, 0, 0, 2, 0, 0, 0, 52, 2, 0, 0, 0, 0, 0, 8, 64, 0, 0, 0, 55, 2, 0, 0,
        0, 0, 0, 8, 28, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 63, 0, 0, 0, 4, 0, 0, 0, 16,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 63, 0, 0, 0, 4, 0, 0, 0, 255, 0, 0, 0, 60, 2,
        0, 0, 0, 0, 0, 14, 57, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 15, 0, 0,
        0, 4, 0, 0, 0, 4, 0, 0, 0, 67, 2, 0, 0, 0, 0, 0, 14, 68, 0, 0, 0, 1, 0, 0, 0, 68, 8, 0, 0,
        5, 0, 0, 15, 72, 1, 0, 0, 45, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 46, 0, 0, 0, 4, 0, 0, 0, 4,
        0, 0, 0, 51, 0, 0, 0, 8, 0, 0, 0, 4, 0, 0, 0, 56, 0, 0, 0, 12, 0, 0, 0, 1, 0, 0, 0, 67, 0,
        0, 0, 16, 0, 0, 0, 56, 1, 0, 0, 76, 8, 0, 0, 2, 0, 0, 15, 48, 0, 0, 0, 17, 0, 0, 0, 0, 0,
        0, 0, 32, 0, 0, 0, 23, 0, 0, 0, 32, 0, 0, 0, 16, 0, 0, 0, 82, 8, 0, 0, 1, 0, 0, 15, 4, 0,
        0, 0, 69, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 105, 110, 116, 0, 95, 95, 65, 82, 82, 65, 89,
        95, 83, 73, 90, 69, 95, 84, 89, 80, 69, 95, 95, 0, 117, 51, 50, 0, 95, 95, 117, 51, 50, 0,
        117, 110, 115, 105, 103, 110, 101, 100, 32, 105, 110, 116, 0, 97, 114, 103, 115, 95, 116,
        0, 102, 110, 97, 109, 101, 0, 102, 108, 97, 103, 115, 0, 99, 104, 97, 114, 0, 116, 121,
        112, 101, 0, 109, 97, 120, 95, 101, 110, 116, 114, 105, 101, 115, 0, 107, 101, 121, 0, 118,
        97, 108, 117, 101, 0, 115, 116, 97, 114, 116, 0, 101, 118, 101, 110, 116, 115, 0, 116, 114,
        97, 99, 101, 95, 101, 118, 101, 110, 116, 95, 114, 97, 119, 95, 115, 121, 115, 95, 101,
        110, 116, 101, 114, 0, 101, 110, 116, 0, 105, 100, 0, 97, 114, 103, 115, 0, 95, 95, 100,
        97, 116, 97, 0, 116, 114, 97, 99, 101, 95, 101, 110, 116, 114, 121, 0, 112, 114, 101, 101,
        109, 112, 116, 95, 99, 111, 117, 110, 116, 0, 112, 105, 100, 0, 117, 110, 115, 105, 103,
        110, 101, 100, 32, 115, 104, 111, 114, 116, 0, 117, 110, 115, 105, 103, 110, 101, 100, 32,
        99, 104, 97, 114, 0, 108, 111, 110, 103, 0, 117, 110, 115, 105, 103, 110, 101, 100, 32,
        108, 111, 110, 103, 0, 99, 116, 120, 0, 116, 114, 97, 99, 101, 112, 111, 105, 110, 116, 95,
        95, 115, 121, 115, 99, 97, 108, 108, 115, 95, 95, 115, 121, 115, 95, 101, 110, 116, 101,
        114, 95, 111, 112, 101, 110, 0, 116, 114, 97, 99, 101, 112, 111, 105, 110, 116, 95, 95,
        115, 121, 115, 99, 97, 108, 108, 115, 95, 95, 115, 121, 115, 95, 101, 110, 116, 101, 114,
        95, 111, 112, 101, 110, 97, 116, 0, 116, 114, 97, 99, 101, 95, 101, 118, 101, 110, 116, 95,
        114, 97, 119, 95, 115, 121, 115, 95, 101, 120, 105, 116, 0, 114, 101, 116, 0, 116, 114, 97,
        99, 101, 112, 111, 105, 110, 116, 95, 95, 115, 121, 115, 99, 97, 108, 108, 115, 95, 95,
        115, 121, 115, 95, 101, 120, 105, 116, 95, 111, 112, 101, 110, 0, 116, 114, 97, 99, 101,
        112, 111, 105, 110, 116, 95, 95, 115, 121, 115, 99, 97, 108, 108, 115, 95, 95, 115, 121,
        115, 95, 101, 120, 105, 116, 95, 111, 112, 101, 110, 97, 116, 0, 112, 105, 100, 95, 116, 0,
        95, 95, 107, 101, 114, 110, 101, 108, 95, 112, 105, 100, 95, 116, 0, 116, 97, 114, 103, 95,
        112, 105, 100, 0, 116, 97, 114, 103, 95, 116, 103, 105, 100, 0, 117, 105, 100, 95, 116, 0,
        95, 95, 107, 101, 114, 110, 101, 108, 95, 117, 105, 100, 51, 50, 95, 116, 0, 116, 97, 114,
        103, 95, 117, 105, 100, 0, 98, 111, 111, 108, 0, 95, 66, 111, 111, 108, 0, 116, 97, 114,
        103, 95, 102, 97, 105, 108, 101, 100, 0, 101, 118, 101, 110, 116, 0, 116, 115, 0, 117, 105,
        100, 0, 99, 97, 108, 108, 101, 114, 115, 0, 99, 111, 109, 109, 0, 95, 95, 117, 54, 52, 0,
        117, 110, 115, 105, 103, 110, 101, 100, 32, 108, 111, 110, 103, 32, 108, 111, 110, 103, 0,
        117, 56, 0, 95, 95, 117, 56, 0, 95, 101, 118, 101, 110, 116, 0, 76, 73, 67, 69, 78, 83, 69,
        0, 47, 104, 111, 109, 101, 47, 122, 104, 117, 108, 105, 47, 100, 97, 116, 97, 47, 108, 105,
        98, 98, 112, 102, 45, 116, 111, 111, 108, 115, 45, 114, 115, 47, 111, 112, 101, 110, 115,
        110, 111, 111, 112, 47, 115, 114, 99, 47, 98, 112, 102, 47, 111, 112, 101, 110, 115, 110,
        111, 111, 112, 46, 98, 112, 102, 46, 99, 0, 105, 110, 116, 32, 116, 114, 97, 99, 101, 112,
        111, 105, 110, 116, 95, 95, 115, 121, 115, 99, 97, 108, 108, 115, 95, 95, 115, 121, 115,
        95, 101, 110, 116, 101, 114, 95, 111, 112, 101, 110, 40, 0, 32, 32, 117, 54, 52, 32, 105,
        100, 32, 61, 32, 98, 112, 102, 95, 103, 101, 116, 95, 99, 117, 114, 114, 101, 110, 116, 95,
        112, 105, 100, 95, 116, 103, 105, 100, 40, 41, 59, 0, 32, 32, 117, 51, 50, 32, 112, 105,
        100, 32, 61, 32, 105, 100, 59, 0, 32, 32, 105, 102, 32, 40, 116, 97, 114, 103, 95, 116,
        103, 105, 100, 32, 38, 38, 32, 116, 97, 114, 103, 95, 116, 103, 105, 100, 32, 33, 61, 32,
        116, 103, 105, 100, 41, 0, 32, 32, 117, 51, 50, 32, 116, 103, 105, 100, 32, 61, 32, 105,
        100, 32, 62, 62, 32, 51, 50, 59, 0, 32, 32, 105, 102, 32, 40, 116, 97, 114, 103, 95, 112,
        105, 100, 32, 38, 38, 32, 116, 97, 114, 103, 95, 112, 105, 100, 32, 33, 61, 32, 112, 105,
        100, 41, 0, 32, 32, 105, 102, 32, 40, 118, 97, 108, 105, 100, 95, 117, 105, 100, 40, 116,
        97, 114, 103, 95, 117, 105, 100, 41, 41, 32, 123, 0, 32, 32, 32, 32, 117, 105, 100, 32, 61,
        32, 40, 117, 51, 50, 41, 98, 112, 102, 95, 103, 101, 116, 95, 99, 117, 114, 114, 101, 110,
        116, 95, 117, 105, 100, 95, 103, 105, 100, 40, 41, 59, 0, 32, 32, 32, 32, 105, 102, 32, 40,
        116, 97, 114, 103, 95, 117, 105, 100, 32, 33, 61, 32, 117, 105, 100, 41, 32, 123, 0, 32,
        32, 32, 32, 115, 116, 114, 117, 99, 116, 32, 97, 114, 103, 115, 95, 116, 32, 97, 114, 103,
        115, 32, 61, 32, 123, 125, 59, 0, 32, 32, 32, 32, 97, 114, 103, 115, 46, 102, 110, 97, 109,
        101, 32, 61, 32, 40, 99, 111, 110, 115, 116, 32, 99, 104, 97, 114, 32, 42, 41, 99, 116,
        120, 45, 62, 97, 114, 103, 115, 91, 48, 93, 59, 0, 32, 32, 32, 32, 97, 114, 103, 115, 46,
        102, 108, 97, 103, 115, 32, 61, 32, 40, 105, 110, 116, 41, 99, 116, 120, 45, 62, 97, 114,
        103, 115, 91, 49, 93, 59, 0, 32, 32, 32, 32, 98, 112, 102, 95, 109, 97, 112, 95, 117, 112,
        100, 97, 116, 101, 95, 101, 108, 101, 109, 40, 38, 115, 116, 97, 114, 116, 44, 32, 38, 112,
        105, 100, 44, 32, 38, 97, 114, 103, 115, 44, 32, 48, 41, 59, 0, 32, 32, 114, 101, 116, 117,
        114, 110, 32, 48, 59, 0, 105, 110, 116, 32, 116, 114, 97, 99, 101, 112, 111, 105, 110, 116,
        95, 95, 115, 121, 115, 99, 97, 108, 108, 115, 95, 95, 115, 121, 115, 95, 101, 110, 116,
        101, 114, 95, 111, 112, 101, 110, 97, 116, 40, 0, 32, 32, 32, 32, 97, 114, 103, 115, 46,
        102, 110, 97, 109, 101, 32, 61, 32, 40, 99, 111, 110, 115, 116, 32, 99, 104, 97, 114, 32,
        42, 41, 99, 116, 120, 45, 62, 97, 114, 103, 115, 91, 49, 93, 59, 0, 32, 32, 32, 32, 97,
        114, 103, 115, 46, 102, 108, 97, 103, 115, 32, 61, 32, 40, 105, 110, 116, 41, 99, 116, 120,
        45, 62, 97, 114, 103, 115, 91, 50, 93, 59, 0, 105, 110, 116, 32, 116, 114, 97, 99, 101,
        112, 111, 105, 110, 116, 95, 95, 115, 121, 115, 99, 97, 108, 108, 115, 95, 95, 115, 121,
        115, 95, 101, 120, 105, 116, 95, 111, 112, 101, 110, 40, 115, 116, 114, 117, 99, 116, 32,
        116, 114, 97, 99, 101, 95, 101, 118, 101, 110, 116, 95, 114, 97, 119, 95, 115, 121, 115,
        95, 101, 120, 105, 116, 32, 42, 99, 116, 120, 41, 32, 123, 0, 32, 32, 117, 51, 50, 32, 112,
        105, 100, 32, 61, 32, 98, 112, 102, 95, 103, 101, 116, 95, 99, 117, 114, 114, 101, 110,
        116, 95, 112, 105, 100, 95, 116, 103, 105, 100, 40, 41, 59, 0, 32, 32, 97, 112, 32, 61, 32,
        98, 112, 102, 95, 109, 97, 112, 95, 108, 111, 111, 107, 117, 112, 95, 101, 108, 101, 109,
        40, 38, 115, 116, 97, 114, 116, 44, 32, 38, 112, 105, 100, 41, 59, 0, 32, 32, 105, 102, 32,
        40, 33, 97, 112, 41, 0, 32, 32, 114, 101, 116, 32, 61, 32, 99, 116, 120, 45, 62, 114, 101,
        116, 59, 0, 32, 32, 105, 102, 32, 40, 116, 97, 114, 103, 95, 102, 97, 105, 108, 101, 100,
        32, 38, 38, 32, 114, 101, 116, 32, 62, 61, 32, 48, 41, 0, 32, 32, 115, 116, 114, 117, 99,
        116, 32, 101, 118, 101, 110, 116, 32, 42, 101, 118, 101, 110, 116, 32, 61, 32, 98, 112,
        102, 95, 114, 105, 110, 103, 98, 117, 102, 95, 114, 101, 115, 101, 114, 118, 101, 40, 38,
        101, 118, 101, 110, 116, 115, 44, 32, 115, 105, 122, 101, 111, 102, 40, 115, 116, 114, 117,
        99, 116, 32, 101, 118, 101, 110, 116, 41, 44, 32, 48, 41, 59, 0, 32, 32, 105, 102, 32, 40,
        33, 101, 118, 101, 110, 116, 41, 0, 32, 32, 101, 118, 101, 110, 116, 45, 62, 112, 105, 100,
        32, 61, 32, 98, 112, 102, 95, 103, 101, 116, 95, 99, 117, 114, 114, 101, 110, 116, 95, 112,
        105, 100, 95, 116, 103, 105, 100, 40, 41, 32, 62, 62, 32, 51, 50, 59, 0, 32, 32, 101, 118,
        101, 110, 116, 45, 62, 117, 105, 100, 32, 61, 32, 98, 112, 102, 95, 103, 101, 116, 95, 99,
        117, 114, 114, 101, 110, 116, 95, 117, 105, 100, 95, 103, 105, 100, 40, 41, 59, 0, 32, 32,
        98, 112, 102, 95, 103, 101, 116, 95, 99, 117, 114, 114, 101, 110, 116, 95, 99, 111, 109,
        109, 40, 38, 101, 118, 101, 110, 116, 45, 62, 99, 111, 109, 109, 44, 32, 115, 105, 122,
        101, 111, 102, 40, 101, 118, 101, 110, 116, 45, 62, 99, 111, 109, 109, 41, 41, 59, 0, 32,
        32, 98, 112, 102, 95, 112, 114, 111, 98, 101, 95, 114, 101, 97, 100, 95, 117, 115, 101,
        114, 95, 115, 116, 114, 40, 38, 101, 118, 101, 110, 116, 45, 62, 102, 110, 97, 109, 101,
        44, 32, 115, 105, 122, 101, 111, 102, 40, 101, 118, 101, 110, 116, 45, 62, 102, 110, 97,
        109, 101, 41, 44, 32, 97, 112, 45, 62, 102, 110, 97, 109, 101, 41, 59, 0, 32, 32, 101, 118,
        101, 110, 116, 45, 62, 102, 108, 97, 103, 115, 32, 61, 32, 97, 112, 45, 62, 102, 108, 97,
        103, 115, 59, 0, 32, 32, 101, 118, 101, 110, 116, 45, 62, 114, 101, 116, 32, 61, 32, 114,
        101, 116, 59, 0, 32, 32, 98, 112, 102, 95, 103, 101, 116, 95, 115, 116, 97, 99, 107, 40,
        99, 116, 120, 44, 32, 38, 115, 116, 97, 99, 107, 44, 32, 115, 105, 122, 101, 111, 102, 40,
        115, 116, 97, 99, 107, 41, 44, 32, 66, 80, 70, 95, 70, 95, 85, 83, 69, 82, 95, 83, 84, 65,
        67, 75, 41, 59, 0, 32, 32, 101, 118, 101, 110, 116, 45, 62, 99, 97, 108, 108, 101, 114,
        115, 91, 48, 93, 32, 61, 32, 115, 116, 97, 99, 107, 91, 49, 93, 59, 0, 32, 32, 101, 118,
        101, 110, 116, 45, 62, 99, 97, 108, 108, 101, 114, 115, 91, 49, 93, 32, 61, 32, 115, 116,
        97, 99, 107, 91, 50, 93, 59, 0, 32, 32, 98, 112, 102, 95, 114, 105, 110, 103, 98, 117, 102,
        95, 115, 117, 98, 109, 105, 116, 40, 101, 118, 101, 110, 116, 44, 32, 48, 41, 59, 0, 32,
        32, 98, 112, 102, 95, 109, 97, 112, 95, 100, 101, 108, 101, 116, 101, 95, 101, 108, 101,
        109, 40, 38, 115, 116, 97, 114, 116, 44, 32, 38, 112, 105, 100, 41, 59, 0, 32, 32, 114,
        101, 116, 117, 114, 110, 32, 116, 114, 97, 99, 101, 95, 101, 120, 105, 116, 40, 99, 116,
        120, 41, 59, 0, 105, 110, 116, 32, 116, 114, 97, 99, 101, 112, 111, 105, 110, 116, 95, 95,
        115, 121, 115, 99, 97, 108, 108, 115, 95, 95, 115, 121, 115, 95, 101, 120, 105, 116, 95,
        111, 112, 101, 110, 97, 116, 40, 0, 48, 58, 50, 58, 48, 0, 48, 58, 50, 58, 49, 0, 48, 58,
        50, 58, 50, 0, 48, 58, 50, 0, 46, 114, 111, 100, 97, 116, 97, 0, 46, 109, 97, 112, 115, 0,
        108, 105, 99, 101, 110, 115, 101, 0, 116, 114, 97, 99, 101, 112, 111, 105, 110, 116, 47,
        115, 121, 115, 99, 97, 108, 108, 115, 47, 115, 121, 115, 95, 101, 110, 116, 101, 114, 95,
        111, 112, 101, 110, 0, 116, 114, 97, 99, 101, 112, 111, 105, 110, 116, 47, 115, 121, 115,
        99, 97, 108, 108, 115, 47, 115, 121, 115, 95, 101, 110, 116, 101, 114, 95, 111, 112, 101,
        110, 97, 116, 0, 116, 114, 97, 99, 101, 112, 111, 105, 110, 116, 47, 115, 121, 115, 99, 97,
        108, 108, 115, 47, 115, 121, 115, 95, 101, 120, 105, 116, 95, 111, 112, 101, 110, 0, 116,
        114, 97, 99, 101, 112, 111, 105, 110, 116, 47, 115, 121, 115, 99, 97, 108, 108, 115, 47,
        115, 121, 115, 95, 101, 120, 105, 116, 95, 111, 112, 101, 110, 97, 116, 0, 159, 235, 1, 0,
        32, 0, 0, 0, 0, 0, 0, 0, 68, 0, 0, 0, 68, 0, 0, 0, 68, 7, 0, 0, 136, 7, 0, 0, 132, 0, 0, 0,
        8, 0, 0, 0, 90, 8, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 34, 0, 0, 0, 125, 8, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 35, 0, 0, 0, 162, 8, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 39, 0, 0, 0, 196, 8, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 40, 0, 0, 0, 16, 0, 0, 0, 90, 8, 0, 0, 26, 0, 0, 0, 0, 0, 0, 0, 75, 2,
        0, 0, 142, 2, 0, 0, 0, 188, 0, 0, 8, 0, 0, 0, 75, 2, 0, 0, 184, 2, 0, 0, 12, 196, 0, 0, 16,
        0, 0, 0, 75, 2, 0, 0, 223, 2, 0, 0, 7, 208, 0, 0, 24, 0, 0, 0, 75, 2, 0, 0, 239, 2, 0, 0,
        7, 132, 0, 0, 48, 0, 0, 0, 75, 2, 0, 0, 239, 2, 0, 0, 17, 132, 0, 0, 56, 0, 0, 0, 75, 2, 0,
        0, 239, 2, 0, 0, 20, 132, 0, 0, 64, 0, 0, 0, 75, 2, 0, 0, 21, 3, 0, 0, 17, 204, 0, 0, 80,
        0, 0, 0, 75, 2, 0, 0, 239, 2, 0, 0, 7, 132, 0, 0, 88, 0, 0, 0, 75, 2, 0, 0, 44, 3, 0, 0, 7,
        140, 0, 0, 112, 0, 0, 0, 75, 2, 0, 0, 44, 3, 0, 0, 16, 140, 0, 0, 120, 0, 0, 0, 75, 2, 0,
        0, 44, 3, 0, 0, 19, 140, 0, 0, 128, 0, 0, 0, 75, 2, 0, 0, 223, 2, 0, 0, 13, 208, 0, 0, 144,
        0, 0, 0, 75, 2, 0, 0, 44, 3, 0, 0, 7, 140, 0, 0, 152, 0, 0, 0, 75, 2, 0, 0, 79, 3, 0, 0,
        17, 148, 0, 0, 192, 0, 0, 0, 75, 2, 0, 0, 79, 3, 0, 0, 7, 148, 0, 0, 200, 0, 0, 0, 75, 2,
        0, 0, 108, 3, 0, 0, 16, 152, 0, 0, 208, 0, 0, 0, 75, 2, 0, 0, 150, 3, 0, 0, 9, 156, 0, 0,
        216, 0, 0, 0, 75, 2, 0, 0, 108, 3, 0, 0, 11, 152, 0, 0, 232, 0, 0, 0, 75, 2, 0, 0, 150, 3,
        0, 0, 9, 156, 0, 0, 248, 0, 0, 0, 75, 2, 0, 0, 177, 3, 0, 0, 19, 224, 0, 0, 0, 1, 0, 0, 75,
        2, 0, 0, 206, 3, 0, 0, 32, 228, 0, 0, 8, 1, 0, 0, 75, 2, 0, 0, 206, 3, 0, 0, 16, 228, 0, 0,
        16, 1, 0, 0, 75, 2, 0, 0, 251, 3, 0, 0, 23, 232, 0, 0, 24, 1, 0, 0, 75, 2, 0, 0, 251, 3, 0,
        0, 16, 232, 0, 0, 64, 1, 0, 0, 75, 2, 0, 0, 31, 4, 0, 0, 5, 236, 0, 0, 96, 1, 0, 0, 75, 2,
        0, 0, 80, 4, 0, 0, 3, 244, 0, 0, 125, 8, 0, 0, 26, 0, 0, 0, 0, 0, 0, 0, 75, 2, 0, 0, 92, 4,
        0, 0, 0, 4, 1, 0, 8, 0, 0, 0, 75, 2, 0, 0, 184, 2, 0, 0, 12, 12, 1, 0, 16, 0, 0, 0, 75, 2,
        0, 0, 223, 2, 0, 0, 7, 24, 1, 0, 24, 0, 0, 0, 75, 2, 0, 0, 239, 2, 0, 0, 7, 132, 0, 0, 48,
        0, 0, 0, 75, 2, 0, 0, 239, 2, 0, 0, 17, 132, 0, 0, 56, 0, 0, 0, 75, 2, 0, 0, 239, 2, 0, 0,
        20, 132, 0, 0, 64, 0, 0, 0, 75, 2, 0, 0, 21, 3, 0, 0, 17, 20, 1, 0, 80, 0, 0, 0, 75, 2, 0,
        0, 239, 2, 0, 0, 7, 132, 0, 0, 88, 0, 0, 0, 75, 2, 0, 0, 44, 3, 0, 0, 7, 140, 0, 0, 112, 0,
        0, 0, 75, 2, 0, 0, 44, 3, 0, 0, 16, 140, 0, 0, 120, 0, 0, 0, 75, 2, 0, 0, 44, 3, 0, 0, 19,
        140, 0, 0, 128, 0, 0, 0, 75, 2, 0, 0, 223, 2, 0, 0, 13, 24, 1, 0, 144, 0, 0, 0, 75, 2, 0,
        0, 44, 3, 0, 0, 7, 140, 0, 0, 152, 0, 0, 0, 75, 2, 0, 0, 79, 3, 0, 0, 17, 148, 0, 0, 192,
        0, 0, 0, 75, 2, 0, 0, 79, 3, 0, 0, 7, 148, 0, 0, 200, 0, 0, 0, 75, 2, 0, 0, 108, 3, 0, 0,
        16, 152, 0, 0, 208, 0, 0, 0, 75, 2, 0, 0, 150, 3, 0, 0, 9, 156, 0, 0, 216, 0, 0, 0, 75, 2,
        0, 0, 108, 3, 0, 0, 11, 152, 0, 0, 232, 0, 0, 0, 75, 2, 0, 0, 150, 3, 0, 0, 9, 156, 0, 0,
        248, 0, 0, 0, 75, 2, 0, 0, 177, 3, 0, 0, 19, 40, 1, 0, 0, 1, 0, 0, 75, 2, 0, 0, 136, 4, 0,
        0, 32, 44, 1, 0, 8, 1, 0, 0, 75, 2, 0, 0, 136, 4, 0, 0, 16, 44, 1, 0, 16, 1, 0, 0, 75, 2,
        0, 0, 181, 4, 0, 0, 23, 48, 1, 0, 24, 1, 0, 0, 75, 2, 0, 0, 181, 4, 0, 0, 16, 48, 1, 0, 64,
        1, 0, 0, 75, 2, 0, 0, 31, 4, 0, 0, 5, 52, 1, 0, 96, 1, 0, 0, 75, 2, 0, 0, 80, 4, 0, 0, 3,
        60, 1, 0, 162, 8, 0, 0, 31, 0, 0, 0, 0, 0, 0, 0, 75, 2, 0, 0, 217, 4, 0, 0, 0, 224, 1, 0,
        8, 0, 0, 0, 75, 2, 0, 0, 41, 5, 0, 0, 13, 88, 1, 0, 16, 0, 0, 0, 75, 2, 0, 0, 41, 5, 0, 0,
        7, 88, 1, 0, 40, 0, 0, 0, 75, 2, 0, 0, 81, 5, 0, 0, 8, 96, 1, 0, 72, 0, 0, 0, 75, 2, 0, 0,
        123, 5, 0, 0, 7, 100, 1, 0, 80, 0, 0, 0, 75, 2, 0, 0, 134, 5, 0, 0, 14, 108, 1, 0, 88, 0,
        0, 0, 75, 2, 0, 0, 152, 5, 0, 0, 7, 112, 1, 0, 112, 0, 0, 0, 75, 2, 0, 0, 152, 5, 0, 0, 19,
        112, 1, 0, 152, 0, 0, 0, 75, 2, 0, 0, 183, 5, 0, 0, 25, 128, 1, 0, 200, 0, 0, 0, 75, 2, 0,
        0, 6, 6, 0, 0, 7, 132, 1, 0, 208, 0, 0, 0, 75, 2, 0, 0, 20, 6, 0, 0, 16, 140, 1, 0, 216, 0,
        0, 0, 75, 2, 0, 0, 20, 6, 0, 0, 43, 140, 1, 0, 224, 0, 0, 0, 75, 2, 0, 0, 20, 6, 0, 0, 14,
        140, 1, 0, 232, 0, 0, 0, 75, 2, 0, 0, 69, 6, 0, 0, 16, 144, 1, 0, 240, 0, 0, 0, 75, 2, 0,
        0, 69, 6, 0, 0, 14, 144, 1, 0, 248, 0, 0, 0, 75, 2, 0, 0, 111, 6, 0, 0, 32, 148, 1, 0, 8,
        1, 0, 0, 75, 2, 0, 0, 111, 6, 0, 0, 3, 148, 1, 0, 24, 1, 0, 0, 75, 2, 0, 0, 170, 6, 0, 0,
        68, 152, 1, 0, 32, 1, 0, 0, 75, 2, 0, 0, 170, 6, 0, 0, 35, 152, 1, 0, 48, 1, 0, 0, 75, 2,
        0, 0, 170, 6, 0, 0, 3, 152, 1, 0, 64, 1, 0, 0, 75, 2, 0, 0, 245, 6, 0, 0, 22, 156, 1, 0,
        72, 1, 0, 0, 75, 2, 0, 0, 245, 6, 0, 0, 16, 156, 1, 0, 80, 1, 0, 0, 75, 2, 0, 0, 17, 7, 0,
        0, 14, 160, 1, 0, 104, 1, 0, 0, 75, 2, 0, 0, 37, 7, 0, 0, 3, 168, 1, 0, 136, 1, 0, 0, 75,
        2, 0, 0, 100, 7, 0, 0, 23, 176, 1, 0, 144, 1, 0, 0, 75, 2, 0, 0, 100, 7, 0, 0, 21, 176, 1,
        0, 152, 1, 0, 0, 75, 2, 0, 0, 132, 7, 0, 0, 23, 180, 1, 0, 160, 1, 0, 0, 75, 2, 0, 0, 132,
        7, 0, 0, 21, 180, 1, 0, 168, 1, 0, 0, 75, 2, 0, 0, 164, 7, 0, 0, 3, 192, 1, 0, 208, 1, 0,
        0, 75, 2, 0, 0, 196, 7, 0, 0, 3, 204, 1, 0, 232, 1, 0, 0, 75, 2, 0, 0, 233, 7, 0, 0, 3,
        228, 1, 0, 196, 8, 0, 0, 31, 0, 0, 0, 0, 0, 0, 0, 75, 2, 0, 0, 3, 8, 0, 0, 0, 244, 1, 0, 8,
        0, 0, 0, 75, 2, 0, 0, 41, 5, 0, 0, 13, 88, 1, 0, 16, 0, 0, 0, 75, 2, 0, 0, 41, 5, 0, 0, 7,
        88, 1, 0, 40, 0, 0, 0, 75, 2, 0, 0, 81, 5, 0, 0, 8, 96, 1, 0, 72, 0, 0, 0, 75, 2, 0, 0,
        123, 5, 0, 0, 7, 100, 1, 0, 80, 0, 0, 0, 75, 2, 0, 0, 134, 5, 0, 0, 14, 108, 1, 0, 88, 0,
        0, 0, 75, 2, 0, 0, 152, 5, 0, 0, 7, 112, 1, 0, 112, 0, 0, 0, 75, 2, 0, 0, 152, 5, 0, 0, 19,
        112, 1, 0, 152, 0, 0, 0, 75, 2, 0, 0, 183, 5, 0, 0, 25, 128, 1, 0, 200, 0, 0, 0, 75, 2, 0,
        0, 6, 6, 0, 0, 7, 132, 1, 0, 208, 0, 0, 0, 75, 2, 0, 0, 20, 6, 0, 0, 16, 140, 1, 0, 216, 0,
        0, 0, 75, 2, 0, 0, 20, 6, 0, 0, 43, 140, 1, 0, 224, 0, 0, 0, 75, 2, 0, 0, 20, 6, 0, 0, 14,
        140, 1, 0, 232, 0, 0, 0, 75, 2, 0, 0, 69, 6, 0, 0, 16, 144, 1, 0, 240, 0, 0, 0, 75, 2, 0,
        0, 69, 6, 0, 0, 14, 144, 1, 0, 248, 0, 0, 0, 75, 2, 0, 0, 111, 6, 0, 0, 32, 148, 1, 0, 8,
        1, 0, 0, 75, 2, 0, 0, 111, 6, 0, 0, 3, 148, 1, 0, 24, 1, 0, 0, 75, 2, 0, 0, 170, 6, 0, 0,
        68, 152, 1, 0, 32, 1, 0, 0, 75, 2, 0, 0, 170, 6, 0, 0, 35, 152, 1, 0, 48, 1, 0, 0, 75, 2,
        0, 0, 170, 6, 0, 0, 3, 152, 1, 0, 64, 1, 0, 0, 75, 2, 0, 0, 245, 6, 0, 0, 22, 156, 1, 0,
        72, 1, 0, 0, 75, 2, 0, 0, 245, 6, 0, 0, 16, 156, 1, 0, 80, 1, 0, 0, 75, 2, 0, 0, 17, 7, 0,
        0, 14, 160, 1, 0, 104, 1, 0, 0, 75, 2, 0, 0, 37, 7, 0, 0, 3, 168, 1, 0, 136, 1, 0, 0, 75,
        2, 0, 0, 100, 7, 0, 0, 23, 176, 1, 0, 144, 1, 0, 0, 75, 2, 0, 0, 100, 7, 0, 0, 21, 176, 1,
        0, 152, 1, 0, 0, 75, 2, 0, 0, 132, 7, 0, 0, 23, 180, 1, 0, 160, 1, 0, 0, 75, 2, 0, 0, 132,
        7, 0, 0, 21, 180, 1, 0, 168, 1, 0, 0, 75, 2, 0, 0, 164, 7, 0, 0, 3, 192, 1, 0, 208, 1, 0,
        0, 75, 2, 0, 0, 196, 7, 0, 0, 3, 204, 1, 0, 232, 1, 0, 0, 75, 2, 0, 0, 233, 7, 0, 0, 3,
        252, 1, 0, 16, 0, 0, 0, 90, 8, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 25, 0, 0, 0, 46, 8, 0, 0, 0,
        0, 0, 0, 16, 1, 0, 0, 25, 0, 0, 0, 52, 8, 0, 0, 0, 0, 0, 0, 125, 8, 0, 0, 2, 0, 0, 0, 0, 1,
        0, 0, 25, 0, 0, 0, 52, 8, 0, 0, 0, 0, 0, 0, 16, 1, 0, 0, 25, 0, 0, 0, 58, 8, 0, 0, 0, 0, 0,
        0, 162, 8, 0, 0, 1, 0, 0, 0, 80, 0, 0, 0, 37, 0, 0, 0, 64, 8, 0, 0, 0, 0, 0, 0, 196, 8, 0,
        0, 1, 0, 0, 0, 80, 0, 0, 0, 37, 0, 0, 0, 64, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 3, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0, 0,
        0, 0, 75, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 9, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 144, 2,
        0, 0, 0, 0, 0, 0, 176, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0,
        24, 0, 0, 0, 0, 0, 0, 0, 17, 0, 0, 0, 1, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 64, 4, 0, 0, 0, 0, 0, 0, 112, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 52, 0, 0, 0, 1, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 176, 5, 0, 0, 0, 0, 0, 0, 112, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 89, 0, 0, 0, 1, 0, 0, 0, 6, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32, 7, 0, 0, 0, 0, 0, 0, 248, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 123, 0, 0, 0, 1, 0, 0,
        0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 24, 9, 0, 0, 0, 0, 0, 0, 248, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 159, 0,
        0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 11, 0, 0, 0, 0, 0, 0,
        72, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 167, 0, 0, 0, 1, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 88, 12, 0,
        0, 0, 0, 0, 0, 48, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 173, 0, 0, 0, 1, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 136, 12, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 159, 1, 0, 0, 9, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 144, 12, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 3, 0,
        0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 198, 1, 0, 0, 9, 0, 0, 0, 64, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 208, 12, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0,
        2, 0, 0, 0, 4, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 239, 1, 0, 0, 9,
        0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 13, 0, 0, 0, 0, 0, 0, 64, 0,
        0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 5, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0,
        21, 2, 0, 0, 9, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 80, 13, 0, 0, 0,
        0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 6, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0,
        0, 0, 0, 0, 0, 61, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        144, 13, 0, 0, 0, 0, 0, 0, 224, 14, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 66, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 112, 28, 0, 0, 0, 0, 0, 0, 44, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    ];
}
